
        <fieldset>
            <legend><?php echo $this->gabarit->getLabel(); ?></legend>

            <div style="display:none;" class="sort-box">
                <div style="background-color: white; padding: 0px 5px; font-size: 11px; display: block; margin-top: -25px;" class="expand-collapse fr"><a style="font-size:11px" href="#" class="expand disabled">Tout déplier</a> / <a style="font-size:11px" href="#" class="collapse">Tout replier</a></div>

<?php
    foreach ($this->values as $value) {

        $this->_buildChamps($value);
?>
                <fieldset class="sort-elmt">
                    <legend><?php echo $this->valueLabel; ?></legend>

                    <div>
                        <div class="line">
                            <label for="visible-<?php echo $this->gabarit->getId() . '-' . (isset($value['id']) ? $value['id'] : 0) . '-' . (isset($value['id_version']) ? $value['id_version'] : 1) ?>">Visible</label>
                            <input type="checkbox" id="visible-<?php echo $this->gabarit->getId() . '-' . (isset($value['id']) ? $value['id'] : 0) . '-' . (isset($value['id_version']) ? $value['id_version'] : 1) ?>" class="changevisible"<?php echo (isset($value['visible']) && $value['visible'] ? ' checked="checked"' : '') ?> />
                            <input type="hidden" value="<?php echo (isset($value['visible']) && $value['visible'] ? 1 : 0) ?>" name="visible[]" />
                        </div>

                        <div<?php echo (isset($value['visible']) && $value['visible'] ? '' : ' class="translucide"') ?>>
                            <input type="hidden" name="id_<?php echo $this->gabarit->getTable() . '[]" value="' . (isset($value['id']) ? $value['id'] : '') ?>" />

                            <?php echo $this->champsHTML; ?>
                        </div>
                    </div>

                    <div style="clear:both;">
                        <div class="btn-a gradient-blue fr"><a href="#" class="delBloc" <?php echo ( count($this->values) > 1 ? '' : ' style="display: none;"' ) ?>>
                            <img src="app/back/img/white/trash_stroke_16x16.png" border="0" alt="supprimer"/></a></div>
                        <div class="btn-a gradient-blue"><a href="#" class="sort-move"><img src="app/back/img/deplacer.png" alt="Déplacer" /></a></div>
                    </div>
                </fieldset>
<?php
    }
?>
                <div class="buttonright"><div class="btn-a gradient-blue"><a class="addBloc" href="#">Ajouter un bloc</a></div></div>
            </div>
        </fieldset>