






<script type="text/javascript" charset="utf-8"> 
    var root = "";
    function redirectAfter(nbSeconds, url)
    {
        setTimeout('redirect("' + url + '")', nbSeconds * 1000);
    }
    
    function redirect(url)
    {
        document.location.href = url;
        return false;
    }

    $(function(){
        root = $('base').attr('href');
    
        
        

        
        /*
         * Object ui 
         * Permet d'ajouter des éléments graphiques
         */
        
        var ui = {
            appendEffect : "<?php echo $this->appConfig->get('ui-appendeffect', 'gabarit'); ?>",
            appendDelay : <?php echo $this->appConfig->get('ui-appenddelay', 'gabarit'); ?>,
            
            init : function () {
                this._initForm();
                this._initAutoComplete();
            },
            
            _initForm : function () {
                $('#form-project').find('form').form();
                $('#form-project').find('form').formToTable({
                    callback : function (data) {
                        document.body.style.cursor='wait';
                        $.getJSON("project/copy.html", {dir : data.chemin}, function(data){
                            document.body.style.cursor='auto';
                            redirect(root + 'project/change.html?id=' + data.id)
                        });
                        
                    }
                })
            },
            _initAutoComplete : function () {
                $( ".ui-form-autocomplete" ).autocomplete({
                    source: function( request, response ) {
                        var params = this.element.attr("id").split('-');
                        $.getJSON( "project/auto-complete.html?type=" + params[0], request, function( data, status, xhr ) {
                            response( data.items );
                            
                        });
                    },
                    minLength: 0
                });
            }
            
            
        }
        
        ui.init()
        
        
       
    }); 
        
        
  
 
</script> 


<div id="form-project">
    <form method="post" id="projet-form" class="ui-form ui-widget">
        <div id="" style="outline: 0px none; width: 425px;position: relative;overflow: visible;" class="ini-bloc ui-dialog ui-widget ui-widget-content ui-corner-all">

            <!-- PERMET DE DIRE QUE LENREGISTREMENT SE FERA SUR LA BDD DE LAPPLI ET PAS SU LA BDD DU PROJET -->
            <input type="hidden" value="" name="base-main" />

            <div class="ui-dialog-titlebar ui-widget-header ui-corner-all ui-helper-clearfix" style="margin-bottom: 5px;">
                <span class="ui-dialog-title"><?php echo $this->_("Paramètres Général"); ?></span>
                <div class="group-tools">
                    <span class="ui-icon ui-icon-trash"></span>
                </div>

            </div>

            <div class="ui-form-elem">

                <label for=""><?php echo $this->_("Nom"); ?></label>
                <input type="text" value="" name="nom" />
            </div>
            <div class="ui-form-elem">
                <label for=""><?php echo $this->_("Chemin"); ?></label>
                <input type="text" value="" name="chemin" class="ui-form-autocomplete" id="chemin-autocomplete" />
            </div>

            <div class="ui-form-elem">
                <label for=""></label>
                <button type="submit" class="fg-button fg-button-custom ui-state-default ui-corner-all">Ajouter</button>
            </div>



        </div>
    </form>
</div>


