






<script type="text/javascript" charset="utf-8"> 
    $(document).ready(function() {
        
        
        
        
        var progress = {
            totalItem : 0,
            loadedItem : 0,
            init : function () {
                $("#dialog-progress").dialog({
                    autoOpen : false
                });
                $( "#progressbar" ).progressbar({
                    value: 0
                });
            },
            open : function () {
                $( "#progressbar" ).progressbar({
                    value: 0
                });
                progress.loadedItem = 0
                $("#dialog-progress").dialog('open');
            },
            close : function () {
                
                $("#dialog-progress").dialog('close');
            },
            progress : function (nbItem) {
                var prog = (progress.loadedItem  + nbItem) / progress.totalItem * 100
                progress.loadedItem += nbItem;
                $( "#progressbar" ).progressbar({
                    value: prog
                });
            }
        };
        
        
        
        
        
        
        
        /*
         * Object ui 
         * Permet d'ajouter des éléments graphiques
         */
        
        var ui = {
            appendEffect : "<?php echo $this->appConfig->get('ui-appendeffect', 'gabarit'); ?>",
            appendDelay : <?php echo $this->appConfig->get('ui-appenddelay', 'gabarit'); ?>,
            
            init : function () {
                this._initDialog();
                this._initEvent();
                this._initFormToTable();
                this._initGui();
                this._initData();
                
            },
            
            _initDialog : function () {
                
                var $formTemplate = $('#template-gab_champ-form').tmpl({add : true})
                .appendTo("#dialog-gab_champ")
                $formTemplate.form();
                
                
                $.fx.speeds._default = 1000;
                
                
                
                
                $( "#dialog-confirm" ).dialog({
                    resizable: false,
                    autoOpen: false,
                    height: "auto",
                    width: 400,
                    modal: true
                });
                
                
                $('.dialog-form').dialog({
                    resizable: false,
                    autoOpen: false,
                    height: "auto",
                    width: 450,
                    modal: false,
                    show: "explode",
                    hide: "explode",
                    buttons: {
                        "Ajouter": function() {
                            var myDialog = $( this ).attr('id').split('-')
                            
                            switch($( this ).attr('id')) {
                                case 'dialog-gab_gabarit':
                                    $('#' + myDialog[1] + '-form').formToTable('send');
                                    $('.gabarit-select').selectLoad();
                                    $('input[name="name"]', this).focus()
                                    $('input[name="name"]', this).select();
                                    break;
                                case 'dialog-gab_champ':
                                case 'dialog-gab_champ_group':
                                case 'dialog-gab_bloc':
                                    var selected = $('.gabarit-select', this).val(); 
                                    var tab = $( "#tabs-" + selected ).index();
                                    $( "#tabs-" + selected ).parent().tabs('select', tab-1);
                                    $('#' + myDialog[1] + '-form').formToTable('send');
                                    break;
                                
                            }
                        },
                        "Ajouter et fermer": function() {
                            var myDialog = $( this ).attr('id').split('-')
                            
                            switch($( this ).attr('id')) {
                                case 'dialog-gab_gabarit':
                                    $('#' + myDialog[1] + '-form').formToTable('send');
                                    $('.gabarit-select').selectLoad();
                                    break;
                                case 'dialog-gab_champ':
                                case 'dialog-gab_champ_group':
                                case 'dialog-gab_bloc':
                                    var selected = $('.gabarit-select', this).val(); 
                                    var tab = $( "#tabs-" + selected ).index();
                                    $( "#tabs-" + selected ).parent().tabs('select', tab-1);
                                    $('#' + myDialog[1] + '-form').formToTable('send');
                                    break;
                            }
                    
                            $( this ).dialog( "close" );
                        },
                        "Fermer" : function() {
                            $( this ).dialog( "close" );
                        }
                    },
                    open: function() {
                        switch($( this ).attr('id')) {
                            case 'dialog-gab_gabarit':
                                $('input[name="name"]', this).focus()
                                break;
                            case 'dialog-gab_champ':
                            case 'dialog-gab_champ_group':
                            case 'dialog-gab_bloc':
                                var selected = $( "#tabs-layout-0" ).tabs( "option", "selected" );
                                var tab = $( "#tabs-layout-0 .tabs" ).eq(selected).attr('id').split('-');
                                var optionIndex = $('.gabarit-select:first option:[value=' + tab[1] + ']', this).index()
                                $('.gabarit-select', this).selectmenu('value', optionIndex); 
                                break;
                        }
                    },
                    close: function() {
                
                    }
                });
            },
            
            _initEvent : function () {
                
                $('.tabs').live('click', function(e) {
                    e.stopPropagation();
                    if($(this).hasClass('animate-processing'))
                        return true;
                    $(this).addClass('animate-processing')
                    
                    var divStateHightight = $('<div class="ui-state-highlight">').appendTo("body")
                    var divStateDefault = $('<div class="ui-state-default">').appendTo("body")
                    var backgroundHightight = divStateHightight.css('background-color');
                    var backgroundDefault = divStateDefault.css('background-color');
                    
                    divStateHightight.remove();
                    divStateDefault.remove();
                    if(backgroundHightight == $(this).css('background-color'))
                        return true;
                    //                    $('.tabs').css("ui-state-highlight")
                    $('.tabs').animate({'background-color' : backgroundDefault}, 500);
                    
                    $(this).animate({'background-color' : backgroundHightight}, 500, function() {
                        $(this).removeClass('animate-processing');
                    });
                    
                })
                    
                $('.field-tools .ui-icon-pencil').live('click', function () {
                    var field = $(this).parents('.fields:first');
                    if($('.gab_champ-form-edit', field).is(':visible')) {
                        $('.gab_champ-form-edit', field).hide(ui.appendEffect, ui.appendDelay)
                    } else {
                        $('.gab_champ-form-edit', field).show(ui.appendEffect, ui.appendDelay);
                    }
                })
                
                $('.field-tools .ui-icon-trash').live('click', function () {
                    var id = $(this).parents('.fields:first').attr('id').substr(7);
                    var $field = $(this).parents('.fields:first');
                    $( "#dialog-confirm" ).dialog({
                        buttons: {
                            "Supprimer cet élément": function() {
                                $.post("gabarit/delete.html", {table : 'gab_champ',id : id }); 
                                $field.hide(ui.appendEffect, ui.appendDelay);
                                $( this ).dialog( "close" );
                            },
                            "Annuler": function() {
                                $( this ).dialog( "close" );
                            }
                        }
                            
                    });

                    $( "#dialog-confirm" ).dialog('open');
                });
                
                
                
                $('.fields li.ui-state-default').live('dblclick', function () {
                    var field = $(this).parents('.fields:first');
                    if($('.gab_champ-form-edit', field).is(':visible')) {
                        $('.gab_champ-form-edit', field).hide(ui.appendEffect, ui.appendDelay)
                    } else {
                        $('.gab_champ-form-edit', field).show(ui.appendEffect, ui.appendDelay);
                    }
                });
            
                $('.open-dialog').click(function () {
                    var myDialog = $(this).attr('id').split('-')
                    var type = myDialog[1];
                    $('.dialog-form#dialog-' + type).dialog('open');
                })
            },
            
            _initFormToTable : function () {
                $(' #gab_champ-form').formToTable({
                    callback : function(data) {
                        ui.addField(data.id_parent, data.name, data.type, data.typedonnee, data.typesql, data.oblig, data.media, data.id, 0, true, data.type_parent)
                    }
                });
        
                $('#gab_champ_group-form').formToTable({
                    callback : function(data) {
                        ui.addGroup(data.id_gabarit, data.label, null, data.id, true, 'group');
                    }
                });
                
                $('#gab_bloc-form').formToTable({
                    callback : function(data) {
                        ui.addGroup(data.id_gabarit, data.label, null, data.id, true, 'bloc');
                    }
                });
        
                $('#gab_gabarit-form').formToTable({
                    callback : function(data) {
                        ui.addGabarit(data.id, data.name, true, data.id_parent)
                    }
                });
            },
            
            _initGui : function () {
                //SELECT UI
                $('.dialog-form .ui-select:not(.ui-select-load)' ).selectmenu({
                    width : 250,
                    style : "dropdown",
                    maxHeight: 200
                });
                
                $(".dialog-form form").form();
                
                
                
                //all hover and click logic for buttons
                $(".dialog-form .fg-button-custom:not(.ui-state-disabled)")
                .hover(
                function(){ 
                    $(this).addClass("ui-state-hover"); 
                },
                function(){ 
                    $(this).removeClass("ui-state-hover"); 
                })
                .mousedown(function(event){
                    $(this).parents('.fg-buttonset-single:first').find(".fg-button-custom.ui-state-active").removeClass("ui-state-active");
                    if( $(this).is('.ui-state-active.fg-button-toggleable, .fg-buttonset-multi .ui-state-active') ){ $(this).removeClass("ui-state-active"); }
                    else { $(this).addClass("ui-state-active"); }	
                })
                .mouseup(function(event){
                    if(! $(this).is('.fg-button-toggleable, .fg-buttonset-single .fg-button-custom,  .fg-buttonset-multi .fg-button-custom') ){
                        $(this).removeClass("ui-state-active");
                    }
                }).click(function(event){
                    event.preventDefault();
                });
            },
            
            _initData : function () {
                $('.gabarit-select').selectLoad();
            },
            
            
            addGroup : function (gabaritId, title, items, id, calculOrdre, type) {
                var $group = $('#template-group').tmpl( {id : id, title : title, items : items, type : type} )
                .appendTo( "#tabs-" + gabaritId + " > .groups" )
                .hide()
                .show(ui.appendEffect, ui.appendDelay);
                
                
                
                $group.parents(".groups:first").sortable({
                    placeholder: "ui-state-highlight",
                    handle : "div.ui-dialog-titlebar:first",
                    items: "div.group:not(.no-sortable)",
                    update : function () { 
                        var order = $(this).sortable('serialize'); 
                        $.getJSON("gabarit/process-sortable.html?table=gab_champ_group&id_parent=" + gabaritId + "&"+order); 
                    } 
                });
                
                if(calculOrdre) {
                    var order = $group.parents(".groups:first").sortable('serialize'); 
                    $.getJSON("gabarit/process-sortable.html?table=gab_champ_group&id_gabarit=" + gabaritId + "&"+order); 
                }
                
                
                
                $( ".connectedSortable", $group ).sortable({
                    connectWith: ".connectedSortable",
                    placeholder: "ui-state-highlight",
                    handle : "li:first",
                    start : function (event, ui) {
                        //                        ui.item.find('.gab_champ-form-edit:first').hide(ui.appendEffect, ui.appendDelay);
                    },
                    update : function () { 
                        var order = $(this).sortable('serialize'); 
                        var type = $(this).parents('.group:first').attr('id').substr(0, $(this).parents('.group:first').attr('id').indexOf('_'))
                        $.getJSON("gabarit/process-sortable.html?table=gab_champ&type_parent=" + type + "&id_parent=" + gabaritId + "&id_group=" + id + "&"+order); 
                    } 
                })

            },

            addField : function (id_gabarit, name, type, typedonnee, typesql, oblig, media, id, id_group, calculOrdre, type_parent) {
                var data = {
                    name : name,
                    type : type,
                    typedonnee : typedonnee,
                    typesql : typesql,
                    media : media,
                    oblig : oblig,
                    id : id
                }; 
                
                var selectorGroup = "";
                if(type_parent == 'bloc') {
                    type_parent = 'bloc';
                    id_group = id_gabarit;
                    selectorGroup = "#bloc_" + id_group + " .mysortable";
                    
                }
                else {
                    type_parent = 'group';
                    selectorGroup = "#tabs-" + id_gabarit + " .groups #group_" + id_group + " .mysortable:last";
                }
                
                var $field = $('#template-field').tmpl( {id : id, name : name, type : type, typedonnee : typedonnee, typesql : typesql, data : data} )
                .appendTo( selectorGroup )
                .hide()
                .show(ui.appendEffect, ui.appendDelay, function () {
                    if(calculOrdre) {
                        $( selectorGroup ).sortable('refresh'); 
                        var order = $( selectorGroup ).sortable('serialize'); 
                        var type = $( selectorGroup ).parents('.group:first').attr('id').substr(0, $(this).parents('.group:first').attr('id').indexOf('_'))
                        $.getJSON("gabarit/process-sortable.html?table=gab_champ&type_parent=" + type + "&id_parent=" + id_gabarit + "&id_group=0&"+order); 
                    }
                });
                
                
                
                //SELECT UI
                $('.ui-select:not(.ui-select-load)', $field.find('form')).selectmenu({
                    width : 250,
                    style : "dropdown",
                    maxHeight: 200
                });
                
                //all hover and click logic for buttons
                $(".fg-button-custom:not(.ui-state-disabled)", $field.find('form'))
                .hover(
                function(){ 
                    $(this).addClass("ui-state-hover"); 
                },
                function(){ 
                    $(this).removeClass("ui-state-hover"); 
                })
                .mousedown(function(event){
                    $(this).parents('.fg-buttonset-single:first').find(".fg-button-custom.ui-state-active").removeClass("ui-state-active");
                    if( $(this).is('.ui-state-active.fg-button-toggleable, .fg-buttonset-multi .ui-state-active') ){ $(this, nRow).removeClass("ui-state-active"); }
                    else { $(this).addClass("ui-state-active"); }	
                })
                .mouseup(function(event){
                    if(! $(this).is('.fg-button-toggleable, .fg-buttonset-single .fg-button-custom,  .fg-buttonset-multi .fg-button-custom') ){
                        $(this).removeClass("ui-state-active");
                    }
                }).click(function(event){
                    event.preventDefault();
                });
                
                $field.find('form').form();
                $field.find('form').formToTable({
                    callback : function (data) {
                        $($field).find('li:first span:first').html(data.name)
                        $($field).find('.gab_champ-form-edit:first').hide(ui.appendEffect, ui.appendDelay);
                    }
                })


            },

            addGabarit : function (id, title, calculOrdre, id_tab) {
                if($("#tabs-layout-" + id_tab ).length == 0) {
                    var layout = '';
                    if(id_tab == 0)
                        layout = "#main-layout";
                    else {
                        layout = "#tabs-" + id_tab;
                    }
                        
                    $('#template-tabs').tmpl({id : id_tab})
                    .prependTo(layout)
                }
                var optionsTabs  = {};
                if(id_tab != 0) {
                    optionsTabs = {collapsible: true }
                }
                $('#template-gabarit-title').tmpl( {id : id, title : title} )
                .appendTo( "#tabs-layout-" + id_tab + " ul:first" )
                var $tabContent = $('#template-gabarit-content').tmpl( {id : id} )
                .appendTo( "#tabs-layout-" + id_tab  )
                $( "#tabs-layout-" + id_tab ).tabs("destroy");
                $( "#tabs-layout-" + id_tab ).tabs(optionsTabs).find( ".ui-tabs-nav" ).sortable({ 
                    axis: "x",
                    update : function () { 
                        var order = $(this).sortable('serialize'); 
                        $.getJSON("gabarit/process-sortable.html?table=gab_gabarit&"+order, function () {
                            $('.gabarit-select').selectLoad();
                        }); 
                    } 
                });
                $( "#tabs-layout-" + id_tab ).tabs('select', $( "#tabs-layout-" + id_tab ).tabs("length") - 1);
                
                if(calculOrdre) {
                    var order = $( "#tabs-layout-" + id_tab ).tabs(optionsTabs).find( ".ui-tabs-nav" ).sortable('serialize'); 
                    $.getJSON("gabarit/process-sortable.html?table=gab_gabarit&"+order, function () {
                        $('.gabarit-select').selectLoad();
                    }); 
                }
                
                //Ajouter un groupe dans un gabarit
                ui.addGroup(id, "Uncategorized", null, 0, false, 'group');
            }
        }
        
        
        /*
         * Object loader
         * Permet de charger l'interface
         */
        var loader = {
            gabarits: function(p) {
                for(i in p.data) {
                    ui.addGabarit(p.data[i].id, p.data[i].name, false, p.data[i].id_parent)
                }
            },
            fieldGroups: function(p) {
                for(i in p.data) {
                    ui.addGroup(p.data[i].id_gabarit, p.data[i].label, null, p.data[i].id, false, p.data[i].type)
                }
            },
            fields: function(p) {
                for(i in p.data) {
                    ui.addField(p.data[i].id_parent, p.data[i].name, p.data[i].type, p.data[i].typedonnee, p.data[i].typesql, p.data[i].oblig, p.data[i].media, p.data[i].id, p.data[i].id_group, true, p.data[i].type_parent)
                }
                ui.init();
            }
        }
        
        /*
         * Initialisation de l'interface
         */
        //        ui.init()
        
        /*
         * Récupération des informations en base sur les gabarits
         */
        document.body.style.cursor='wait';
        $.getJSON("gabarit/load.html", function(data){
            for(i in data) {
                if (data[i]) {
                    loader[i].call(this, data[i]);
                    progress.progress(1)
                }
            }
            document.body.style.cursor='auto';
        });
    }); 
        
        
  
 
</script> 






<!-- DIALOGS -->
<div class="dialogs">
    <div id="dialog-gab_gabarit" class="dialog-form" title="Créer un gabarit">

        <form id="gab_gabarit-form" method="post" class="ui-form ui-widget">

            <div class="ui-form-elem">
                <label for="">Gabarit parent</label>
                <select name="id_parent" id="gabarit-select-3" class="ui-select ui-select-load ui-select-fac gabarit-select">

                </select>
            </div>
            <div class="ui-form-elem">
                <label for="">Nom</label>
                <input type="text" value="" name="name" />
            </div>



        </form>
    </div>



    <div id="dialog-gab_champ_group" class="dialog-form" title="Créer un groupe de champs">

        <form id="gab_champ_group-form" method="post" class="ui-form ui-widget">

            <div class="ui-form-elem">
                <label for="">Gabarit</label>
                <select name="id_gabarit" id="gabarit-select-2" class="ui-select ui-select-load gabarit-select">

                </select>
            </div>
            <div class="ui-form-elem">
                <label for="">Nom</label>
                <input type="text" value="" name="label" />
            </div>



        </form>
    </div>

    <div id="dialog-gab_bloc" class="dialog-form" title="Créer un groupe dynamique">

        <form id="gab_bloc-form" method="post" class="ui-form ui-widget">

            <div class="ui-form-elem">
                <label for="">Gabarit</label>
                <select name="id_gabarit" id="gabarit-select-4" class="ui-select ui-select-load gabarit-select">

                </select>
            </div>
            <div class="ui-form-elem">
                <label for="">Nom</label>
                <input type="text" value="" name="label" />
            </div>



        </form>
    </div>


    <div id="dialog-gab_champ" class="dialog-form" title="Créer un champ">
    </div>

    <div id="dialog-confirm" title="Supprimer cet élément ?">
        <p>
            <span class="ui-icon ui-icon-alert" style="float:left; margin:0 7px 20px 0;"></span>
            Cet élément va etre supprimer de façon permanente et ne pourra etre récupéré. Est tu sur ?
        </p>
    </div>

    <div id="dialog-progress" title="Progression">
        <p>
            <!-- PROGRESSBAR -->
        <div id="progressbar"></div>
        <!-- END PROGRESSBAR -->
        </p>
    </div>
</div>
<!-- END DIALOGS -->


<!-- TEMPLATE JQUERY -->
<script id="template-group" type="text/x-jquery-tmpl"> 

    <div id="${type}_${id}" style="outline: 0px none; width: 100%;position: relative;overflow: visible;margin-bottom: 10px;" class="group ui-dialog ui-widget ui-widget-content ui-corner-all {{if id == 0}}no-sortable{{/if}}">
        <div class="ui-dialog-titlebar ui-widget-header ui-corner-all ui-helper-clearfix">
            <span class="ui-dialog-title">${title}</span>
            <div class="group-tools">
                <span class="ui-icon ui-icon-pencil"></span>
                <span class="ui-icon ui-icon-trash"></span>
            </div>

        </div>
        <div class="ui-dialog-content ui-widget-content" style="overflow: visible;">
            <ul style="" id="" class="mysortable connectedSortable">
                {{if items}}
                {{tmpl(items) "#template-field"}}
                {{/if}}
            </ul>
        </div>
        <div class="clear"></div>
    </div>

</script>

<script id="template-field" type="text/x-jquery-tmpl"> 
    <div id="fields_${id}" class="fields">
        <li class="ui-state-default">
            <span>${name}</span> 
            <div class="field-tools">
                <span class="ui-icon ui-icon-pencil"></span>
                <span class="ui-icon ui-icon-trash"></span>
            </div>

        </li>
        <div class="gab_champ-form-edit" style="display: none">
            {{tmpl() "#template-gab_champ-form"}}
        </div>
    </div>
</script>


<script id="template-gabarit-content" type="text/x-jquery-tmpl">
    <div id="tabs-${id}" class="tabs">


        <div class="mysortable groups">
        </div>


        <div class="clear"></div>
    </div>
</script>

<script id="template-gabarit-title" type="text/x-jquery-tmpl">
    <li id="gabarits-${id}"><a href="#tabs-{{html id}}">${title}</a></li>
</script>

<script id="template-gab_champ-form" type="text/x-jquery-tmpl">
    <form method="post" id="{{if add}}gab_champ-form{{else}}gab_champ-form-${data.id}{{/if}}" class="ui-form ui-widget">


        {{if add}}
        <div class="ui-form-elem">
            <label for="">Gabarit</label>
            <select name="id_parent" id="gabarit-select-1" class="ui-select ui-select-load gabarit-select">
            </select>
        </div>
        {{/if}}

        {{if data}}
        <input name="id" type="hidden" value="${data.id}" />
        {{/if}}

        <div class="ui-form-elem">
            <label for="">Label</label>
            <input name="name" type="text" value="{{if data}}${data.name}{{/if}}" />
        </div>


        <div class="ui-form-elem">
            <label for="">Type</label>
            <div style="float:left;">
                <select name="type" id="" class="ui-select" style="">
                    <?php
                    foreach ($this->gabChampType as $champType) {
                        ?>
                        <option {{if data}}{{if data.type == "<?php echo $champType['code']; ?>"}}selected="selected"{{/if}}{{/if}} value="<?php echo $champType['code']; ?>"><?php echo $champType['code']; ?></option>
                        <?php
                    }
                    ?>
                </select>
            </div>
            <!--            <div>Paramétrage</div>-->
        </div>
        <div class="ui-form-elem">
            <label for="">Type de donnée</label>

            <select name="typedonnee" id="" class="ui-select">
                <?php
                foreach ($this->gabChampTypeDonnee as $champTypeDonnee) {
                    ?>
                    <option {{if data}}{{if data.typedonnee == "<?php echo $champTypeDonnee['code']; ?>"}}selected="selected"{{/if}}{{/if}} value="<?php echo $champTypeDonnee['code']; ?>"><?php echo $champTypeDonnee['code']; ?></option>
                    <?php
                }
                ?>
            </select>
        </div>
        <div class="ui-form-elem">
            <label for="">Type sql</label>

            <select name="typesql" id="" class="ui-select">
                <?php
                foreach ($this->gabChampTypeSql as $champTypeSql) {
                    ?>
                    <option {{if data}}{{if data.typesql == "<?php echo $champTypeSql; ?>"}}selected="selected"{{/if}}{{/if}} value="<?php echo $champTypeSql; ?>"><?php echo $champTypeSql; ?></option>
                    <?php
                }
                ?>
            </select>
        </div>
        <div class="ui-form-elem">
            <label for=""></label>
            <div name="oblig" class="fg-buttonset fg-buttonset-custom fg-buttonset-single ui-helper-clearfix">
                <button name="oblig" class="fg-button fg-button-double fg-button-custom ui-state-default ui-priority-primary ui-corner-left {{if data}}{{if data.oblig == 'oblig'}}ui-state-active{{/if}}{{else}}ui-state-active{{/if}}">Obligatoire</button>
                <button name="fac" class="fg-button fg-button-double fg-button-custom ui-state-default ui-priority-primary ui-corner-right {{if data}}{{if data.oblig == 'fac'}}ui-state-active{{/if}}{{/if}}" style="clear:none;">Facultatif</button>
            </div>
        </div>
        <div class="ui-form-elem">
            <label for="">Média</label>

            <select name="media" id="" class="ui-select">
                <?php
                foreach ($this->gabChampMedia as $champMedia) {
                    ?>
                    <option {{if data}}{{if data.media == "<?php echo $champMedia; ?>"}}selected="selected"{{/if}}{{/if}} value="<?php echo $champMedia; ?>"><?php echo $champMedia; ?></option>
                    <?php
                }
                ?>
            </select>
        </div>

        {{if add}}
        {{else}}
        <div class="ui-form-elem">
            <label for=""></label>
            <button type="submit" class="fg-button fg-button-custom ui-state-default ui-corner-all">Enregistrer</button>
        </div>
        {{/if}}

    </form>
</script>

<!-- TABS -->
<script id="template-tabs" type="text/x-jquery-tmpl">

    <div id="tabs-layout-${id}" class="tabs-layout"  style="">
        <ul>

        </ul>

    </div>
</script>

<!-- END TABS -->

<script id="template-menu-gabarit" type="text/x-jquery-tmpl">
    <div class="fg-buttonset fg-buttonset-custom ui-helper-clearfix">
        <button class="fg-button fg-button-custom ui-state-default ui-corner-all open-dialog" id="add-gab_gabarit">Créer un gabarit</button>
        <button class="fg-button fg-button-custom ui-state-default ui-corner-all open-dialog" id="add-gab_bloc">Créer un groupe dynamique</button>
        <button class="fg-button fg-button-custom ui-state-default ui-corner-all open-dialog" id="add-gab_champ_group">Créer un groupe de champs</button>
        <button class="fg-button fg-button-custom ui-state-default ui-corner-all open-dialog" id="add-gab_champ">Créer un champ</button>
        <button class="fg-button fg-button-custom ui-state-default ui-corner-all open-dialog ui-state-disabled" id="import-template-gabarit">Importer un template</button>
    </div>
</script>


<!-- END TEMPLATE JQUERY -->
