
<fieldset><legend><?php echo $this->gabarit->getLabel(); ?></legend><div style="display:none;" class="sort-box">

        <?php
        foreach ($this->values as $value) {
            $this->_buildChamps($value);
            ?>
            <fieldset class="sort-elmt" style="margin-left:30px;"><legend><?php echo $this->valueLabel; ?></legend>
                <div>
                    <div class="line">
                        <label for="visible-<?php echo $this->gabarit->getId() . '-' . (isset($value['id']) ? $value['id'] : 0) . '-' . (isset($value['id_version']) ? $value['id_version'] : 1) ?>">Visible</label>
                        <input type="checkbox" id="visible-<?php echo $this->gabarit->getId() . '-' . (isset($value['id']) ? $value['id'] : 0) . '-' . (isset($value['id_version']) ? $value['id_version'] : 1) ?>" class="changevisible"<?php echo (isset($value['visible']) && $value['visible'] ? ' checked="checked"' : '') ?> />
                        <input type="hidden" value="<?php echo (isset($value['visible']) && $value['visible'] ? 1 : 0) ?>" name="visible[]" />
                    </div><div<?php echo (isset($value['visible']) && $value['visible'] ? '' : ' class="translucide"') ?>>
                        <input type="hidden" name="id_<?php echo $this->gabarit->getTable() . '[]" value="' . (isset($value['id']) ? $value['id'] : '') ?>" />

                        <?php echo $this->champsHTML; ?>
                    </div></div>
                <div>
                    <div class="btn gradient-blue fr"><a href="#" class="delBloc<?php echo ( count($value) > 1 ? '' : ' translucide' ) ?>">
                            <img src="img/back/white/trash_stroke_16x16.png" border="0" alt="supprimer"/></a></div>
                    <div class="btn gradient-blue"><a href="#" class="sort-move"><img src="img/back/deplacer.png" alt="Déplacer" /></a></div>
                </div>
            </fieldset>
            <?php
        }
        ?>
        <div class="buttonright"><div class="btn gradient-blue"><a class="addBloc" href="#">Ajouter un bloc</a></div></div>
    </div></fieldset>