<?php echo '<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9" xmlns:mobile="http://www.google.com/schemas/sitemap-mobile/1.0">'; ?>
<?php foreach ($this->pages as $page) { ?>
	<url>
		<loc><?php echo $this->Url . $page['path'] ?></loc>
                <mobile:mobile/>
		<lastmod><?php echo $page['lastmod']; ?></lastmod>
		<priority><?php echo $page['importance'] > 9 ? 1 : '0.' . $page['importance']; ?></priority>
	</url>
<?php } ?>
</urlset>
