<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="fr" lang="fr">
    <head>
        <title><?php echo $this->seo->getTitle(); ?></title>
        <meta name="description" content="<?php echo $this->seo->getDescription(); ?>" />
        <meta name="keywords" lang="fr" content="<?php echo $this->seo->showKeywords(); ?>" />


        <meta charset="UTF-8" />
        <meta name="language" content="fr" />
        <meta name="robots" content="<?php echo $this->seo->getIndex(); ?>index, <?php echo $this->seo->getFollow(); ?>follow, all" />
        <meta name="googlebot" content="<?php echo $this->seo->getIndex(); ?>index, <?php echo $this->seo->getFollow(); ?>follow, all" />

        <meta name="msvalidate.01" content="" />
        <meta name="y_key" content="" />
        <meta name="google-site-verification" content="" />
        <meta name="author" content="Solire" />
        <base href="<?php echo $this->Url; ?>" />



        <?php echo $this->cssComponents; ?>
        <link rel="stylesheet" type="text/css" href="css/config.css" media="all" />

        <?php echo $this->jsComponents; ?>
        <script type="text/javascript">
            //<![CDATA[

            function showColor() {
                var background = $('<div class="ui-state-active">').css('background-color');
                $(".odd").css('background-color', background)
                    
                $(".odd").illuminate({
                    'intensity': '0.2',
                    'blink': 'false'
                });
            }

            $(document).ready(function(){
                
                $('#ThemeRoller').themeswitcher({
                    height: 400,
                    width: 215,
                    buttonPreText: 'Thème: ',
                    initialText: 'Changer de thème',
                    cookieName: 'jquery-ui-theme',
                    expires: 365, 
                    path:'/',
                    onSelect : function() {
                        //                        setTimeout("showColor()", 1000);
                    }
                });
                
                
                var mainToolbar = {
                    init : function () {
                        mainToolbar.initMenu()
                        mainToolbar.initButtons()
                        mainToolbar.initSelects()
                        
                    },
                    
                    initMenu : function() {
                        //Menu hierarchique
                        $('#hierarchy-menu').fgmenu({
                            content: $('#hierarchy-menu').next().html(),
                            crumbDefaultText: "Menu",
                            maxHeight: 250,
                            backLink: false
                        });
                        
                        mainToolbar.loadMenuTemplate('<?php echo isset($_REQUEST["controller"]) ? $_REQUEST["controller"] : ""; ?>');

                        
                    },
                    loadMenuTemplate : function (nameTemplate) {
                        $('.buttonset-add-custom').empty();
                        if($('#template-menu-' + nameTemplate).length == 1)
                            $('#template-menu-' + nameTemplate).tmpl()
                        .appendTo('.buttonset-add-custom')
                            
                        mainToolbar.initButtons()
                    },
                    
                    initButtons : function() {
                        //Style button
                        $(".main-toolbar .fg-button-custom:not(.ui-state-disabled)")
                        .hover(
                        function(){ 
                            $(this).addClass("ui-state-hover"); 
                        },
                        function(){ 
                            $(this).removeClass("ui-state-hover"); 
                        })
                        .mousedown(function(event){
                            $(this).parents('.fg-buttonset-single:first').find(".fg-button-custom.ui-state-active").removeClass("ui-state-active");
                            if( $(this).is('.ui-state-active.fg-button-toggleable, .fg-buttonset-multi .ui-state-active') ){ $(this).removeClass("ui-state-active"); }
                            else { $(this).addClass("ui-state-active"); }	
                        })
                        .mouseup(function(event){
                            if(! $(this).is('.fg-button-toggleable, .fg-buttonset-single .fg-button-custom,  .fg-buttonset-multi .fg-button-custom') ){
                                $(this).removeClass("ui-state-active");
                            }
                        }).click(function(event){
                            event.preventDefault();
                        });
                    },
                    
                    initSelects : function() {
                        //SELECT UI
                        $('.main-toolbar .ui-select:not(.ui-select-load)' ).selectmenu({
                            width : 150,
                            style : "dropdown",
                            maxHeight: 200
                        });
                    }
                }
                mainToolbar.init()
                
                
                

            });
            //]]>
        </script>


    </head>
    <body role="document">

        <div id="global">

            <header>

                <div class="main-toolbar" style="height: 50px;position: relative">

                    <div class="fg-toolbar ui-widget-header ui-corner-bottom ui-helper-clearfix">



                    </div>
                    <div style="position:fixed;width: 100%;">
                        <div style="position: relative;">
                            <div style="position: absolute;right: 280px;float: left;border: none;font-weight: bold;font-size: 24px;margin-top: 8px;text-align: right;" class="ui-widget-header">
                                <?php echo $this->projectName; ?>
                            </div>
                            <div style="position: absolute;right: 25px;height : 21px;padding-top: 8px;padding-bottom: 2px;" class="fg-buttonset fg-buttonset-custom ui-helper-clearfix">
                                <div id="ThemeRoller"   class="fg-button fg-button-custom  ui-widget ui-state-default ui-corner-all" style="padding-right : 2px;width: 200px;"></div>
                            </div>



                            <div class="buttonset-add">

                                <div class="fg-buttonset fg-buttonset-custom ui-helper-clearfix">


                                    <input type="hidden" id="menu-action" />
                                    <a tabindex="0" href="#news-items-2" class="fg-button fg-button-custom fg-button-icon-right ui-widget ui-state-default ui-corner-all" style="height : 21px;padding-top: 8px;padding-bottom: 2px" id="hierarchy-menu"><span class="ui-icon ui-icon-triangle-1-s"></span><?php echo $this->_("Menu"); ?></a>
                                    <div id="news-items-2" class="fg-menu-hidden">
                                        <ul>

                                            <li><a href="#"><?php echo $this->_("Choix du projet"); ?></a>
                                                <ul>
                                                    <li><a href="project/create.html"><strong><?php echo $this->_("Nouveau projet"); ?></strong></a></li>
                                                    <?php
                                                    
                                                    foreach ($this->gabProjects as $project) {
                                                        ?>
                                                        <li><a href="project/change.html?id=<?php echo $project['id']; ?>"><?php echo $project['nom']; ?></a></li>
                                                        <?php
                                                    }
                                                    ?>

                                                </ul> 
                                            </li>
                                            <?php if (isset($_SESSION['project']) && $_SESSION['project'] != null) { ?>
                                                <li><a href="#"><?php echo $this->_("ini"); ?></a>
                                                    <ul>
                                                        <?php
                                                        foreach ($this->myInis as $ini) {
                                                            ?>
                                                            <li><a href="ini/edit.html?name=<?php echo urlencode($ini); ?>"><?php echo $this->_("Edition"); ?> <?php echo $ini; ?></a></li>
                                                            <?php
                                                        }
                                                        ?>
                                                    </ul> 
                                                </li>

                                                <li><a href="#"><?php echo $this->_("Gabarit"); ?></a>
                                                    <ul>
                                                        <li><a href="gabarit/start.html"><?php echo $this->_("Edition des gabarits") ?></a></li>
                                                    </ul> 
                                                </li>
                                                <li><a href="version/general.html"><?php echo $this->_("Gestion des versions"); ?></a>
                                                </li>
                                                <li><a href="project/param.html"><?php echo $this->_("Configuration du projet"); ?></a>
                                                </li>
                                                <li><a href="#"><?php echo $this->_("Déploiement du projet"); ?></a>
                                                    <ul>
                                                        <li><a href="deployment/general.html"><?php echo $this->_("Mise à jour"); ?></a>
                                                        </li>
                                                        <li><a href="deployment/general.html"><?php echo $this->_("Backup"); ?></a>
                                                            <ul>
                                                                <li><a href="deployment/general.html"><?php echo $this->_("Base de données"); ?></a>
                                                                </li>
                                                                <li><a href="deployment/general.html"><?php echo $this->_("Fichiers"); ?></a>
                                                                </li>
                                                            </ul>
                                                        </li>
                                                    </ul>

                                                </li>
                                            <?php } ?>
                                        </ul> 

                                    </div>

                                </div>

                                <div class="buttonset-add-custom fg-buttonset-custom ui-helper-clearfix"></div>

                            </div>

                        </div>
                    </div>


                </div>

            </header>




            <div id="main-layout">

                <?php $this->content(); ?>

            </div>
            <footer role="contentinfo">



            </footer>

        </div>


        <script type="text/javascript">
            var _gaq = _gaq || [];
            _gaq.push(['_setAccount', '']);
            _gaq.push(['_trackPageview']);

            (function() {
                var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
                ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
                var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
            })();

        </script>
    </body>
</html>





