


<h1>Tableau de bord</h1>

<?php $this->add('breadcrumbs.phtml'); ?>

<!--<h2>Liens rapides</h2>

<?php
foreach ($this->pages as $idGabarit => $pagesGabarit) {
    if (!$pagesGabarit["gabarit"]["creable"])
        continue;
    ?>
                    <div class="btn btn-shortcut fl">
                        <a href="page/display.html?id_gabarit=<?php echo $pagesGabarit["gabarit"]["id"] ?>" class="" title="">
                            <img src="img/back/gray_dark/document_alt_stroke_24x32.png" alt="">
                            <b>Créer un<?php echo $pagesGabarit["gabarit"]["genre"] == "f" ? 'e' : '' ?> <?php echo $pagesGabarit["gabarit"]["label"] ?></b>
                        </a>
                    </div>
    <?php
}
?>


<div class="cb"></div>

<hr>-->

<div id="columns">
    <ul id="column1" class="column">
        <li class="widget gradient-green" id="intro">
            <div class="widget-head gradient-green">
                <h3>Introduction</h3>
            </div>
            <div class="widget-content">
                <p>
                    Le tableau de bord vous permet de visualiser les dernières pages éditées et créées par type de page. Vous pouvez réorganiser chaque bloc du tableau de bord, l'état de celui-ci sera sauvegardé pour votre utilisateur.
                </p>
            </div>
        </li>
    </ul>
    <ul id="column1" class="column">
        <li class="widget gradient-green"  id="resume">
            <div class="widget-head gradient-green">
                <h3>Résumé</h3>
            </div>
            <div class="widget-content">

                <?php
                $nbGab = 0;
                foreach ($this->pages as $idGabarit => $pagesGabarit) {
                    $nbGab++;
                    ?>
                    <div style="margin-top: 10px;">
                        <span class="number"><?php echo $pagesGabarit["gabarit"]["nbpages"] ?></span><?php echo $pagesGabarit["gabarit"]["label"] ?>
                    </div>
                    <?php
                    if ($nbGab != count($this->pages)) {
                        ?>
                        <hr>
                        <?php
                    } else {
                        ?>
                        <br />
                        <?php
                    }
                    ?>

                    <?php
                }
                ?>


            </div>
        </li>

    </ul>
    <?php foreach ($this->pages as $idGabarit => $pagesGabarit) {
        ?>
        <ul id="column1" class="column">

            <li class="widget gradient-blue" id="gabarit-<?php echo $idGabarit ?>">
                <div class="widget-head gradient-blue">
                    <h3><?php echo $pagesGabarit["gabarit"]["label"] ?></h3>
                </div>
                <div class="widget-content">


                    <h4>Dernières pages créées</h4>
                    <ul>
                        <?php foreach ($pagesGabarit["pages"] as $page) {
                            ?>
                            <li class="<?php echo $page->getMeta("visible") ? '' : 'translucide' ?>">
                                <a href="page/display.html?id_gab_page=<?php echo $page->getMeta("id") ?>"><?php echo $page->getMeta("titre") ?></a>
                                <div class="fr">
                                    <?php
                                    if ($page->getMeta("rewriting") != "") {
                                        if ($page->getGabarit()->getMake_hidden()
                                                || $this->utilisateur->get("niveau") == "solire"
                                                || !$page->getMeta("visible")
                                        ) {
                                            ?>
                                            <div style="margin-left: 6px;margin-top: -4px;">
                                                <label style="color:#A1A1A1;text-shadow:none;margin-left:10px;" for="visible-<?php echo $page->getMeta("id"); ?>-<?php echo $page->getMeta("id_version"); ?>">Visible : </label>
                                                <input class="visible-lang visible-lang-<?php echo $page->getMeta("id") . '-' . $page->getMeta("id_version"); ?>" value="<?php echo $page->getMeta("id") . '|' . $page->getMeta("id_version"); ?>" id="visible-<?php echo $page->getMeta("id"); ?>-<?php echo $page->getMeta("id_version"); ?>" type="checkbox" <?php echo ($page->getMeta("visible") ? 'checked="checked"' : ''); ?> />
                                            </div>
                                            <?php
                                        }
                                    } else {
                                        ?>
                                        <span class="notification gradient-red" style="margin-left: 6px;">Non traduit</span>
                                        <?php
                                    }
                                    ?>
                                </div>
                                <div class="board-human-time"><?php echo Tools::RelativeTime(strtotime($page->getMeta("date_crea"))); ?></div>
                            </li>
                            <?php
                        }
                        ?>
                    </ul>
                    <hr />
                    <h4>Dernières pages éditées</h4>
                    <ul>
                        <?php foreach ($pagesGabarit["pages_mod"] as $page) {
                            ?>
                            <li class="<?php echo $page->getMeta("visible") ? '' : 'translucide' ?>">
                                <a href="page/display.html?id_gab_page=<?php echo $page->getMeta("id") ?>"><?php echo $page->getMeta("titre") ?></a>
                                <div class="fr">
                                    <?php
                                    if ($page->getMeta("rewriting") != "") {
                                        if ($page->getGabarit()->getMake_hidden()
                                                || $this->_utilisateur->get("niveau") == "solire"
                                                || !$page->getMeta("visible")
                                        ) {
                                            ?>
                                            <div style="margin-left: 6px;margin-top: -4px;">
                                                <label style="color:#A1A1A1;text-shadow:none;margin-left:10px;" for="visible-<?php echo $page->getMeta("id"); ?>-<?php echo $page->getMeta("id_version"); ?>-m">Visible : </label>
                                                <input class="visible-lang visible-lang-<?php echo $page->getMeta("id") . '-' . $page->getMeta("id_version"); ?>" value="<?php echo $page->getMeta("id") . '|' . $page->getMeta("id_version"); ?>" id="visible-<?php echo $page->getMeta("id"); ?>-<?php echo $page->getMeta("id_version"); ?>-m" type="checkbox" <?php echo ($page->getMeta("visible") ? 'checked="checked"' : ''); ?> />
                                            </div>
                                            <?php
                                        }
                                    } else {
                                        ?>
                                        <span class="notification gradient-red" style="margin-left: 6px;">Non traduit</span>
                                        <?php
                                    }
                                    ?>
                                </div>
                                <div class="board-human-time"><?php echo Tools::RelativeTime(strtotime($page->getMeta("date_modif"))); ?></div>
                            </li>
                            <?php
                        }
                        ?>
                    </ul>
                </div>
            </li>
        </ul>
        <?php
    }
    ?>



</div>
