<fieldset><legend><?php echo $this->gabarit->getName(); ?>(s)</legend>

    <?php
    foreach ($this->champs as $champ) {
        $value_champ = isset($value[$champ['name']]) ? $value[$champ['name']] : '';
        $id_champ = (isset($this->meta['id_version']) ? $this->meta['id_version'] : '') . (isset($value['id']) ? $value['id'] : 0);
        echo $this->_buildChamp($champ, $value_champ, $id_champ, $this->uploadPath, $this->idGabPage);
    }
    ?>

</fieldset>