<script type="text/javascript">
    $(document).ready(function(){
        
        
        //SELECT UI
        $('.ui-form .ui-select:not(.ui-select-load)' ).selectmenu({
            width : 250,
            style : "dropdown",
            maxHeight: 200
        });
    
        
        $("form").form();
        $("button.ui-form-button").button();
        
        
        // run the currently selected effect
        function runEffect($elem) {
            // get effect type from 
            var selectedEffect = $elem.val();
            var selectedDelay = $elem.parents('.ui-form-elem').next().find('input').val();

            // most effect types need no options passed by default
            var options = {};
            // some effects have required parameters
            if ( selectedEffect === "scale" ) {
                options = { percent: 100 };
            } else if ( selectedEffect === "size" ) {
                options = { to: { width: 280, height: 185 } };
            }

            $elem.parents('.ini-bloc:first').hide( selectedEffect, options, selectedDelay);
            // run the effect
            $elem.parents('.ini-bloc:first').show( selectedEffect, options, selectedDelay);
        };

        

        // set effect from select menu value
        $( ".ui-effect" ).change(function() {
            runEffect($(this));
            return false;
        });

        
        
    });
</script>
<form method="post" class="ui-form">

    <?php
    foreach ($this->fieldsets as $fieldset) {
        if (!isset($fieldset['fields']))
            continue;
        ?>
        <div id="" style="outline: 0px none; width: 425px;position: relative;overflow: visible;" class="ini-bloc ui-dialog ui-widget ui-widget-content ui-corner-all {{if id == 0}}no-sortable{{/if}}">
            <div class="ui-dialog-titlebar ui-widget-header ui-corner-all ui-helper-clearfix" style="margin-bottom: 5px;">
                <span class="ui-dialog-title"><?php echo $fieldset['legend']; ?></span>
                <div class="group-tools">
                    <span class="ui-icon ui-icon-trash"></span>
                </div>

            </div>

            <?php
            foreach ($fieldset['fields'] as $field) {
                list($group, $label) = explode('----', $field['name']);
                ?>
                <div class="ui-form-elem">
                    <label for="<?php echo $field['name']; ?>"><?php echo $label; ?></label>
                    <?php
                    if (substr($label, -6) == "effect") {
                        ?>
                        <select name="<?php echo $field['name']; ?>" class="ui-select ui-effect" id="">
                            <option <?php echo $field['value'] == "blind" ? 'selected="selected"' : '' ?> value="blind">Blind</option>
                            <option <?php echo $field['value'] == "bounce" ? 'selected="selected"' : '' ?> value="bounce">Bounce</option>
                            <option <?php echo $field['value'] == "clip" ? 'selected="selected"' : '' ?> value="clip">Clip</option>
                            <option <?php echo $field['value'] == "drop" ? 'selected="selected"' : '' ?> value="drop">Drop</option>
                            <option <?php echo $field['value'] == "explode" ? 'selected="selected"' : '' ?> value="explode">Explode</option>
                            <option <?php echo $field['value'] == "fold" ? 'selected="selected"' : '' ?> value="fold">Fold</option>
                            <option <?php echo $field['value'] == "highlight" ? 'selected="selected"' : '' ?> value="highlight">Highlight</option>
                            <option <?php echo $field['value'] == "puff" ? 'selected="selected"' : '' ?> value="puff">Puff</option>
                            <option <?php echo $field['value'] == "pulsate" ? 'selected="selected"' : '' ?> value="pulsate">Pulsate</option>
                            <option <?php echo $field['value'] == "scale" ? 'selected="selected"' : '' ?> value="scale">Scale</option>
                            <option <?php echo $field['value'] == "shake" ? 'selected="selected"' : '' ?> value="shake">Shake</option>
                            <option <?php echo $field['value'] == "slide" ? 'selected="selected"' : '' ?> value="slide">Slide</option>
                        </select>
                    <?php } else { ?>
                        <input type="text" value="<?php echo $field['value']; ?>" name="<?php echo $field['name']; ?>" />
                        <?php
                    }
                    ?>
                </div>
                <?php
            }
            ?>

        </div>
        <?php
    }
    ?>
    <div class="clear"></div>
</div>
<button class="ui-form-button" name="ini-save"><?php echo $this->_("Sauvegarder"); ?></button>
</form>