<ul class="xbreadcrumbs cf" id="breadcrumbs" style="">


    <?php
    foreach ($this->breadCrumbs as $iLink => $link) {
        ?>
        <?php
        if ($iLink == count($this->breadCrumbs) - 1) {
            ?>
            <li class="current">

                <a class="vam"><?php echo $link["label"]; ?></a>

            </li>
            <?php
        } else {
            ?>
            <li class="parent">

                <a class="vam" href="<?php echo $link["url"]; ?>"><?php echo $link["label"]; ?></a>

            </li>
            <?php
        }
        ?>

        <?php
    }
    ?>



</ul>