<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" lang="fr">
    <head>
        <meta http-equiv="Content-Type" content="text/html; text/css; charset=utf-8" />

        <title>Module de gestion du site <?php echo $this->site; ?>
            <?php
            if (isset($this->breadCrumbs) && count($this->breadCrumbs) > 1) {
                ?>
                |
                <?php
                foreach ($this->breadCrumbs as $iLink => $link) {
                    if ($iLink == 0)
                        continue
                        ?>
                    <?php
                    if ($iLink == count($this->breadCrumbs) - 1) {
                        ?>
                        <?php echo $link["label"]; ?>
                        <?php
                    } else {
                        ?>
                        <?php echo $link["label"]; ?> > 
                        <?php
                    }
                    ?>

                    <?php
                }
            }
            ?>
        </title>
        <meta name="AUTHOR" content="SOLIRE" />
        <meta name="ROBOTS" content="noindex, nofollow" />
        <meta name="GOOGLEBOT" content="noindex, nofollow" />

        <meta http-equiv="X-UA-Compatible" content="IE=EmulateIE7" />
        <meta name="viewport" content="width=1220; user-scalable=yes" />

        <base href="<?php echo $this->Url; ?>" />

        <link rel="shortcut icon" href="img/back/favicon.ico" />


        <!--[if lte IE 8]>
        <link rel="stylesheet" href="ie8.css" type="text/css" />
        <![endif]-->

        <!--[if lte IE 7]>
        <link rel="stylesheet" href="ie.css" type="text/css" />
        <![endif]-->

        <!--[if lte IE 6]>
           <link rel="stylesheet" href="ie6.css" type="text/css" />
        <![endif]-->

        <?php echo $this->css; ?>

        <style type="text/css">
            .option1, .option1:disabled {color:#fff; background-color:#3485C9; padding-top:5px;}
            .option2, .option2:disabled {color:#fff; background-color:#67A5D7; padding-top:2px; padding-left:15px;}
            .option3 {font-size:1em; padding-left:40px;}
            .ui-autocomplete {max-height:100px; overflow-y:auto; overflow-x:hidden; padding-right:20px;}
            #tableau td {text-align:center;}
        </style>

        <?php echo $this->javascript; ?>

    </head>
    <body>
        <header>
            <div class="navbar navbar-fixed-top">
                <div class="navbar-inner">
                    <div class="container-fluid">
                        <a href="" class="brand"><img src="img/back/gray_dark/home_16x16.png"> <?php echo $this->site; ?></a>

                        <ul class="nav user_menu pull-right">
                            <li class="hidden-phone hidden-tablet">
                                <ul class="new_items">
                                    <?php
                                    if (count($this->pagesNonTraduites) > 0) {
                                        ?>
                                        <li class="sep dropdown">
                                            <a data-toggle="dropdown" class="dropdown-toggle nav_condensed" href="#"><span class="count_el"><?php echo count($this->pagesNonTraduites); ?></span> contenus non traduits <b class="caret"></b></a>
                                            <ul class="dropdown-menu">
                                                <?php
                                                foreach ($this->pagesNonTraduites as $pageNonTraduite) {
                                                    ?>
                                                    <li><a href="page/display.html?id_gab_page=<?php echo $pageNonTraduite["id"] ?>"> <?php echo $pageNonTraduite["titre"] ?></a></li>
                                                    <?php
                                                }
                                                ?>
                                            </ul>
                                        </li>
                                        <?php
                                    }
                                    ?>

                                </ul>
                            </li>
                            <li class="divider-vertical hidden-phone hidden-tablet"></li>
                            <li class="nav-search fr">
                                <div>
                                    <input type="text" class="search live-search"  placeholder="Recherche" />
                                </div>
                            </li>
                            <li class="divider-vertical hidden-phone hidden-tablet"></li>
                            <li class="dropdown">
                                <a data-toggle="dropdown" style="padding-bottom: 0" class="dropdown-toggle nav_condensed" href="#"><img alt="<?php echo $this->versions[BACK_ID_VERSION]['nom'] ?>" src="img/flags/all/24/<?php echo strtolower($this->versions[BACK_ID_VERSION]['suf']) ?>.png" /> <b class="caret"></b></a>
                                <ul class="dropdown-menu">
                                    <?php
                                    foreach ($this->versions as $version) {
                                        ?>
                                        <li><a href="" onclick="var h = window.location.href;window.location = (h + (h.indexOf('?') != -1 ? '&id_version=<?php echo $version['id'] ?>' : '?id_version=<?php echo $version['id'] ?>'));return false;"><img style="width: 16px; height: 16px;display: block;float: left;margin-top: 1px;" alt="" src="img/flags/all/16/<?php echo strtolower($version['suf']) ?>.png" />&nbsp;&nbsp;<?php echo $version['nom'] ?></a></li>
                                        <?php
                                    }
                                    ?>
                                </ul>
                            </li>

                            <li class="divider-vertical divider-simple hidden-phone hidden-tablet"></li>


                            </li>
                            <li class="dropdown<?php echo $this->controller == "user" ? ' gradient-blue text-light-white' : ''; ?>">
                                <a data-toggle="dropdown" class="dropdown-toggle" href="#"><?php echo $this->utilisateur->get("nom"); ?> <?php echo $this->utilisateur->get("prenom"); ?> <b class="caret"></b></a>
                                <ul class="dropdown-menu">
                                    <li class="<?php echo $this->controller == "user" && $this->action == "start" ? 'active' : ''; ?>"><a href="user/start.html"><b>Mon profil</b></a></li>
                                    <li class="divider"></li>
                                    <li><a href="sign/signout.html"><b>Déconnexion</b></a></li>
                                </ul>
                            </li>


                        </ul>


                        
                        <div class="nav-collapse">
                            <nav>
                                <ul class="nav">
                                    <?php
                                    $mobile = false;
                                    if (count($this->apis) > 1) {
                                        ?>
                                        <li class="dropdown">
                                            <a data-toggle="dropdown" class="dropdown-toggle" style="font-weight:bold;padding:0" href="#"><img style="float:left;margin-top: 9px;margin-left: 4px;" width="26" src="img/back/api/<?php echo $this->api["name"]; ?>.png" /><span class="api-selected" style="padding: 12px 10px 11px 3px;display:inline-block"><?php echo $this->api["label"]; ?> <b class="caret"></b></span></a>
                                            <ul class="dropdown-menu">
                                                <?php
                                                $prefix = "../";
                                                if($this->api["id"] == 1) 
                                                        $prefix = "./";
                                                foreach ($this->apis as $idApi => $api) {
                                                    if ($api["name"] == "mobile") {
                                                        $mobile = true;
                                                    }
                                                    ?>
                                                <li><a href="<?php echo $prefix; ?><?php echo $idApi == 1 ? '' : $api["name"] . "/"; ?>" style="font-weight:bold;" href="#"><img style="float:left;margin-top: 5px;" width="28" src="img/back/api/<?php echo $api["name"]; ?>.png" /><span class="api-selected" style="padding: 10px 10px 11px 14px;display:inline-block"><?php echo $api["label"]; ?></span></a></li>
                                                    <?php
                                                }
                                                ?>
                                        </li>
                                    </ul>
                                    <li class="divider-vertical divider-simple hidden-phone hidden-tablet">&nbsp;</li>
                                    <?php
                                }
                                ?>
                                <?php
                                //Si le tableau de board est activé
                                if ($this->appConfig->get("active", "board")) {
                                    ?>
                                    <li<?php echo $this->controller == "board" ? ' class="gradient-blue text-light-white"' : ''; ?>><a href="board/start.html">Tableau de bord</a></li>

                                    <?php
                                }
                                ?>
                                <li class="divider-vertical divider-simple hidden-phone hidden-tablet"></li>
                                <?php
                                if (count($this->menuPage) > 1) {
                                    ?>
                                    <li class="dropdown<?php echo $this->controller == "page" ? ' gradient-blue text-light-white' : ''; ?>">
                                        <a href="#" class="dropdown-toggle" data-toggle="dropdown"> Pages <b class="caret"></b></a>
                                        <ul class="dropdown-menu">
                                            <?php
                                            foreach ($this->menuPage as $indexMenuPage => $mPage) {
                                                $active = "";
                                                if (isset($_GET["c"]) && $_GET["c"] == $indexMenuPage)
                                                    $active = "active";
                                                ?>
                                                <li class="<?php echo $active; ?>"><a href="page/liste.html?c=<?php echo $indexMenuPage ?>"> <?php echo $mPage["label"] ?></a></li>
                                                <?php
                                            }
                                            ?>
                                        </ul>
                                    </li>
                                    <?php
                                } else {
                                    ?>
                                    <li<?php echo $this->controller == "page" ? ' class="gradient-blue text-light-white"' : ''; ?>><a href="page/liste.html">Pages</a></li>
                                    <?php
                                }
                                ?>


                                <li class="divider-vertical divider-simple hidden-phone hidden-tablet"></li>
                                <li<?php echo $this->controller == "media" ? ' class="gradient-blue text-light-white"' : ''; ?>><a href="media/start.html">Fichiers</a></li>
                                <li class="divider-vertical divider-simple hidden-phone hidden-tablet"></li>
                                <li<?php echo $this->controller == "dashboard" && $_GET["name"] == "translate" ? ' class="gradient-blue text-light-white"' : ''; ?>><a href="dashboard/start.html?name=translate" class="bis">Textes statiques</a></li>
                                <?php
                                if ($this->utilisateur->get("niveau") == "solire") {
                                    ?>
                                    <li class="divider-vertical divider-simple hidden-phone hidden-tablet"></li>
                                    <li<?php echo $this->controller == "dashboard" && $_GET["name"] == "redirection" ? ' class="gradient-blue text-light-white"' : ''; ?>><a href="dashboard/start.html?<?php echo $mobile ? 'name[]=redirection&name[]=redirection_mobile' : 'name=redirection'; ?>" class="bis">Redirection</a></li>

                                    <?php
                                }
                                ?>
                                <?php
                                if ($this->utilisateur->get("niveau") == "solire") {
                                    ?>
                                    <li class="divider-vertical divider-simple hidden-phone hidden-tablet"></li>
                                    <li<?php echo $this->controller == "dashboard" && $_GET["name"] == "back_log" ? ' class="gradient-blue text-light-white"' : ''; ?>><a href="dashboard/start.html?name=back_log" class="bis">Logs</a></li>

                                    <?php
                                }
                                ?>




                                </ul>
                            </nav>    
                        </div>	
                        <div class="cb"></div>

                    </div>

                </div>
            </div>



        </header>
        <div id="global">

            <section>
                <article>
                    <div id="corps">

                        <?php echo $this->content(); ?>
                    </div>
                    <div id="footer">
                        <div class="bloc">
                            <p>Outil de gestion de contenu développé par <a href="http://www.solire.fr" target="_blank">Solire</a>


                            </p>
                        </div>
                    </div>
                </article>

            </section>


        </div>

    </body>
</html>