<?php foreach ($this->files as $file) { ?>
                <tr id="fileid_<?php echo $file['id']; ?>">
                    <td>
                        <a  class="previsu" href="<?php echo $file['path']; ?>" title="<?php echo $file['rewriting']; ?>">
                            <img src="<?php echo $file['path_mini']; ?>" alt="<?php echo $file['rewriting']; ?>" />
                        </a>
                    </td>
                    <td><?php echo $file['poids']; ?></td>
                    <td><?php if (isset($file['width'])) echo $file['width']; ?></td>
                    <td><?php if (isset($file['height'])) echo $file['height']; ?></td>
                    <td><?php echo Tools::formate_date_nombre(substr($file['date_crea'], 0, 10), '-', '/'); ?><br /><?php echo substr($file['date_crea'], 11); ?></td>
                    <td><a href="<?php echo $file['path']; ?>" class="previsu button bleu"><span class="bleu"><img alt="Gérer" src="img/back/voir.png" /></span></a></td>
                </tr>
<?php } ?>