        <div>
            <div class="btn gradient-green">
            <a href="#" id="pickfiles">
                ajouter un fichier
            </a>
                </div>
        </div>

        <table id="tableau" style="width:100%;">
            <thead>
                <tr>
                    <th>&nbsp;</th>
                    <th>Taille</th>
                    <th>Date / Heure</th>
                    <th style="width: 50px;">&nbsp;</th>
                </tr>
            </thead>

            <tbody id="foldercontent">
                
<?php foreach ($this->files as $file) { ?>
                
                <tr id="fileid_<?php echo $file['id']; ?>">
                    <td>
                        <a target="_blank" class="previsu" href="<?php echo $file['path']; ?>" title="<?php echo $file['rewriting']; ?>">
                            <img class="<?php echo $file['class']; ?>" src="<?php echo $file['path_mini']; ?>" alt="<?php echo $file['rewriting']; ?>" />
                        </a>
                    </td>
                    <td><?php echo $file['taille']; ?></td>
                    <td><?php echo Tools::formate_date_nombre(substr($file['date_crea'], 0, 10), '-', '/'); ?><br /><?php echo substr($file['date_crea'], 11); ?></td>
                    <td>
                        <div class="btn gradient-blue">
                            <a href="<?php echo $file['path']; ?>" class="previsu"><img alt="Gérer" src="img/back/voir.png" /></a>
                        </diV>
                        
                    </td>
                </tr>
                
<?php } ?>
                
            </tbody>
        </table>
