<style>
    #tableau td {
        overflow: hidden; /* this is what fixes the expansion */
        white-space: normal;
        word-wrap: break-word;
        max-width: 400px;

    }



</style>


<h1>Gestion des fichiers</h1>

<?php $this->add('breadcrumbs.phtml'); ?>

<div id="mmenu">
<!--    <div id="currentruntime" style="font-size:10px; color:#a1a1a1; font-style:italic; padding: 3px;"></div>-->

    <div style="float:left; margin-right:10px; width:200px; height:40px;">

        <!--<a href="#" class="button vert" id="add_folder">
                                        <span class="vert">ajouter un dossier</span>
                                </a>-->
        <div class="btn gradient-green">
            <a href="#" id="pickfiles">Ajouter un fichier
            </a>
        </div>
    </div>



    <!--<div style="float: left; margin-right: 10px;">
            <a href="#" class="button vert" id="uploadfiles">
                    <span class="vert">charger les fichiers</span>
            </a>
    </div>-->
</div>
<div class="clear"></div>

<div id="folders" style="width: 200px; overflow: hidden; float: left"></div>

<div id="colright" style="min-height: 400px; float: left; width: 76%; margin-left: 20px;">
    <table id="tableau" class="display" style="width:100%;margin:0">
        <thead>
            <tr>
                <th>&nbsp;</th>
                <th>Taille</th>
                <th>Largeur</th>
                <th>Hauteur</th>
                <th>Date / Heure</th>
                <th style="width: 50px;">&nbsp;</th>
            </tr>
        </thead>

        <tbody id="foldercontent">
        </tbody>
    </table>
</div>