<?php
    if (isset($this->gabaritsBtn) && count($this->gabaritsBtn)) {
        foreach ($this->gabaritsBtn as $gabaritGroup) {
?>        
                        <div style="float:left;">
<?php
            /** Group */
            if (count($gabaritGroup["gabarit"]) > 1) {
?>
                            <div class="btn-create-container dropdown">
                                <div class="btn-a btn-create gradient-green  dropdown-toggle">
                                    <a href="#" class="group-gabarit">
                                        <img src="img/white/plus_alt_16x16.png" />
                                        <?php echo $gabaritGroup['label'] ?>
                                    </a>
                                </div>

                                <ul class="dropdown-menu">
<?php
                foreach ($gabaritGroup["gabarit"] as $gabarit) {
                    
                    if ($this->utilisateur->get("niveau") != "solire" && !$gabarit["creable"]) {
                        continue;
                    }
?>        
                                    <li>
                                        <a href="page/display.html?id_gabarit=<?php echo $gabarit['id'] ?>"><?php echo $gabarit['label'] ?></a>
                                    </li>
<?php
                }
?>
                                </ul>
                            </div>

<?php
            }
            /** Gabarit simple */
            else {
?>
                            <div class="btn-a gradient-green" style="float:left;margin-right:10px;">
                                <a href="page/display.html?id_gabarit=<?php echo $gabaritGroup['gabarit'][0]['id'] ?>">
                                    <?php echo $gabaritGroup['label'] . $gabaritGroup['gabarit'][0]["label"] ?>
                                </a>
                            </div>
<?php
            }
?>
                        </div>
<?php
        }
    }
?>
