                            <form action="<?php echo $action; ?>" method="post" enctype="multipart/form-data">
                                <input type="hidden" name="id_gabarit" value="<?php echo $this->_gabarit->getId(); ?>" />
                                <input type="hidden" name="id_gab_page" value="<?php echo $metaId; ?>" />
                                <input type="hidden" name="id_version" value="<?php echo $metaLang; ?>" />
                                <input type="hidden" name="id_api" value="<?php echo $api['id']; ?>" />
                                <input type="hidden" name="id_temp" />

<?php
                            if ($this->_gabarit->getIdParent() > 0 && (is_a($this->getParent(0), "\Slrfw\Model\gabaritPage") || !$this->getMeta('id'))) {
?>
                                <div class="line">
                                    <label for="id_parent"><?php echo $this->_gabarit->getGabaritParent("label"); ?></label>
<?php
                                if ($this->getMeta('id')) {
?>
                                    <select disabled="disabled">
                                        <option><?php echo $this->getParent(0)->getMeta("titre"); ?></option>
                                    </select>
                                    <input type="hidden" name="id_parent" value="<?php echo $this->getParent(0)->getMeta("id"); ?>" />
<?php
                                } else {
?>
                                    <select name="id_parent" id="id_parent-1"<?php if ($this->_gabarit->getId() != $this->_gabarit->getIdParent()) { echo ' class="form-controle form-oblig form-notnul"'; } ?>>
                                        <option value="0">---</option>
<?php
                                    foreach ($this->_gabarit->getParents() as $p) {
                                        $disabled = '';
                                        if (count($p->getChildren()) > 0) {
                                            $disabled = ' disabled="disabled"';
                                        }
?>
                                        <option value="<?php echo $p->getMeta('id'); ?>"<?php echo $disabled; ?> class="option1"><?php echo $p->getMeta('titre'); ?></option>
<?php
                                        foreach ($p->getChildren() as $q) {
                                            $disabled = '';
                                            if (count($q->getChildren()) > 0) {
                                                $disabled = ' disabled="disabled"';
                                            }
?>
                                        <option value="<?php echo $q->getMeta('id'); ?>"<?php echo $disabled; ?> class="option2"><?php echo $q->getMeta('titre'); ?></option>
<?php
                                            foreach ($q->getChildren() as $r) {
?>
                                        <option value="<?php echo $r->getMeta('id'); ?>" class="option3"><?php echo $r->getMeta('titre'); ?></option>
<?php
                                            }
                                        }
                                    }
?>
                                    </select>
<?php
                                }
?>
                                </div>
<?php
                        }
?>

                                <div class="line form-line">
                                    <div<?php echo $noMetaTitre; ?> class="line">
                                        <label for="titre-<?php echo $metaLang; ?>">Titre <span class="required">*</span> </label>
                                        <input type="text" name="titre" id="titre-<?php echo $metaLang; ?>" value="<?php echo isset($this->_meta['titre']) ? $this->_meta['titre'] : ''; ?>" class="form-controle<?php echo $this->_gabarit->getMeta_titre() ? ' form-oblig form-mix' : ''; ?>" />
                                    </div>

                                    <div class="line form-other-line" style="display:none;">
                                        <label class="form-other-flag"></label>
                                        <input type="text" disabled="disabled" class="form-other-elmt" />
                                    </div>
                                </div>

<?php
                            if (isset($this->_version['exotique']) && $this->_version['exotique'] > 0) {
?>
                                <div<?php echo $noMetaTitre; ?> class="line">
                                    <label for="titre_rew-<?php echo $metaLang; ?>">Titre pour le rewriting <span class="required">*</span> </label>
                                    <input type="text" name="titre_rew" id="titre_rew-<?php echo $metaLang; ?>" value="<?php echo isset($this->_meta['titre_rew']) ? $this->_meta['titre_rew'] : ''; ?>" class="<?php echo $this->_gabarit->getMeta_titre() ? 'form-controle form-oblig form-mix' : ''; ?>" />
                                </div>
<?php
                            }
?>

                                <fieldset<?php echo $noMeta; ?>>
                                    <legend>Balise Meta</legend>

                                    <div style="display:none;">
                                        <div class="line form-line">
                                            <div class="line"<?php if ($metaId == 1) {echo ' style="display:none;"';} ?>>
                                                <label for="rewriting-<?php echo $metaLang; ?>">Rewriting<?php echo isset($this->_meta['rewriting']) && $this->_meta['rewriting'] != "" ? ' <span class="required">*</span>' : ''; ?></label>
                                                <input type="text" name="rewriting" id="rewriting-<?php echo $metaLang; ?>" value="<?php echo isset($this->_meta['rewriting']) ? $this->_meta['rewriting'] : ''; ?>" class="form-controle<?php echo isset($this->_meta['rewriting']) && $this->_meta['rewriting'] != "" ? ' form-oblig form-notnul' : ''; ?>" />
                                            </div>

                                            <div class="line form-other-line" style="display:none;">
                                                <label class="form-other-flag"></label>
                                                <input type="text" disabled="disabled" class="form-other-elmt" />
                                            </div>
                                        </div>

                                        <div class="line form-line">
                                            <div class="line">
                                                <label for="bal_title-<?php echo $metaLang; ?>">Title</label>
                                                <input type="text" name="bal_title" id="bal_title-<?php echo $metaLang; ?>" value="<?php echo isset($this->_meta['bal_title']) ? $this->_meta['bal_title'] : ''; ?>" size="80" maxlength="80" class="form-controle" />
                                            </div>

                                            <div class="line form-other-line" style="display:none;">
                                                <label class="form-other-flag"></label>
                                                <input type="text" disabled="disabled" class="form-other-elmt" />
                                            </div>
                                        </div>

                                        <div class="line form-line">
                                            <div class="line">
                                                <label for="bal_descr-<?php echo $metaLang; ?>">Description</label>
                                                <input type="text" name="bal_descr" id="bal_descr-<?php echo $metaLang; ?>" value="<?php echo isset($this->_meta['bal_descr']) ? $this->_meta['bal_descr'] : ''; ?>" size="80" maxlength="250" class="form-controle" />
                                            </div>

                                            <div class="line form-other-line" style="display:none;">
                                                <label class="form-other-flag"></label>
                                                <input type="text" disabled="disabled" class="form-other-elmt" />
                                            </div>
                                        </div>

                                        <div class="line form-line">
                                            <div class="line">
                                                <label for="bal_key-<?php echo $metaLang; ?>">Keywords (<i>séparés par des ,</i>)</label>
                                                <input type="text" name="bal_key" id="bal_key-<?php echo $metaLang; ?>" value="<?php echo isset($this->_meta['bal_key']) ? $this->_meta['bal_key'] : ''; ?>" size="80" maxlength="250" class="form-controle" />
                                            </div>

                                            <div class="line form-other-line" style="display:none;">
                                                <label class="form-other-flag"></label>
                                                <input type="text" disabled="disabled" class="form-other-elmt" />
                                            </div>
                                        </div>

                                        <div class="line">
                                            <label for="author-<?php echo $metaLang; ?>">Auteur Google +</label>

                                            <select name="author" id="author-<?php echo $metaLang; ?>">
                                                <option value="0">-------</option>
<?php
                            foreach ($authors as $author) {
                                $selected = isset($this->_meta['author']) && $this->_meta['author'] == $author["id"] ? true : false;
?>
                                                <option <?php echo $selected ? 'selected="selected"' : ""; ?> value="<?php echo $author["id"]; ?>">
                                                    <?php echo $author["nom_de_lauteur"]; ?>
                                                </option>
<?php
                            }
?>
                                            </select>
                                        </div>

                                        <div class="line">
                                            <label for="importance-<?php echo $metaLang; ?>">Importance (<i>de 0,1 à 0,9</i>)</label>
                                            <select name="importance" class="span1" id="importance-<?php echo $metaLang; ?>">
<?php
                            for ($ii = 1 ; $ii < 10 ; $ii++) {
?>
                                                <option value="<?php echo $ii; ?>"<?php echo isset($this->_meta['importance']) && $ii == $this->_meta['importance'] ? ' selected="selected"' : ''; ?>><?php echo $ii; ?></option>
<?php
                            }
?>
                                            </select>
                                        </div>

                                        <div class="line">
                                            <label for="no_index-<?php echo $metaLang; ?>">No-index</label>
                                            <input type="checkbox" value="1" name="no_index" id="no_index-<?php echo $metaLang; ?>"<?php echo isset($this->_meta['no_index']) && $this->_meta['no_index'] > 0 ? ' checked="checked"' : ''; ?> />
                                        </div>

                                        <div class="line">
                                            <label for="canonical-<?php echo $metaLang; ?>">Url canonical</label>
                                            <input type="text" name="canonical" id="canonical-<?php echo $metaLang; ?>" value="<?php echo isset($this->_meta['canonical']) ? $this->_meta['canonical'] : ''; ?>" class="autocomplete-link"  />
                                        </div>

                                        <fieldset  style="margin-left: 15px<?php echo $noRedirections301; ?>">
                                            <legend>Redirection 301 permanent</legend>

                                            <div style="display:none;">
<?php
                            foreach ($redirections as $redirection) {
?>
                                                <div class="line">
                                                    <label for="301-<?php echo $metaLang; ?>">Url</label>
                                                    <input type="text" name="301[]" id="301-<?php echo $metaLang; ?>" value="<?php echo $redirection; ?>" class=""  />
                                                    <a href="#" class="btn btn-small btn-info disabled fr 301-remove<?php echo count($redirections) == 1 ? ' translucide' : ''; ?>" style="margin-right: 200px" title="Retirer"><i class="icon-minus"></i></a>
                                                </div>
<?php
                            }
?>
                                                <a href="#" class="btn btn-small btn-info fr 301-add" style="margin-right: 200px" title="Ajout une URL"><i class="icon-plus"></i></a>
                                            </div>

                                        </fieldset>
                                    </div>
                                </fieldset>

                                <input type="hidden" name="id_<?php echo $this->_gabarit->getTable(); ?>" value="<?php echo isset($this->_values['id']) ? $this->_values['id'] : ''; ?>" />

<?php
                            foreach ($allchamps as $name_group => $champs) {
?>
                                <fieldset>
                                    <legend><?php echo $name_group; ?></legend>

                                    <div<?php echo $metaId ? ' style="display:none;"' : ''; ?>>
<?php
                                foreach ($champs as $champ) {
                                    if($champ["type"] == "GMAP") {
                                        if(isset($this->_values[$champ['name'] . "_lat"])) {
                                            $value = array(
                                                "lat"          =>  $this->_values[$champ['name'] . "_lat"],
                                                "lng"         =>  $this->_values[$champ['name'] . "_lng"],
                                                "zoom"     =>  $this->_values[$champ['name'] . "_zoom"],
                                            );
                                        } else {
                                            $value = array(
                                                "lat"          =>  "",
                                                "lng"         =>  "",
                                                "zoom"     =>  "",
                                            );
                                        }
                                    } else {
                                        $value = isset($this->_values[$champ['name']]) ? $this->_values[$champ['name']] : '';
                                    }
                                    
                                        $id = isset($this->_meta['id_version']) ? $this->_meta['id_version'] : '';
                                        echo $this->_buildChamp($champ, $value, $id, $metaId);
                                }
?>
                                    </div>
                                </fieldset>
<?php
                            }

                            foreach ($this->_blocs as $bloc) {
                                echo $bloc->buildForm($metaId, $this->getMeta('id_version'));
                            }
?>

                                
                                
                                <div class="buttonfixed">
                                    <div class="btn-group btn-group-vertical">
                                        <a title="Valider" class="btn btn-small btn-success formajaxsubmit" href="#"><i class="icon-ok"></i> Valider</a><br /><br />
                                        <a title="Importer" class="btn btn-small btn-success uploader_popup" href="#"><i class="icon-folder-open"></i> Importer</a><br /><br />
                                        <?php
                                            if ($this->_gabarit->getView()) {
                                        ?>
                                        <a title="Prévisualiser" class="btn btn-small btn-success formprev" href="#"><i class="icon-camera"></i> Prévisualiser</a><br /><br />
                                        <?php } ?>
                                        <a title="Quitter" class="btn btn-warning  btn-small back-to-list" href="<?php echo $retour . ($metaId ? '?id_gab_page=' . $metaId : ''); ?>"><i class="icon-warning-sign"></i> Quitter</a>
                                    </div>
                                </div>
                                
                            </form>



