<div class="line<?php echo $this->champ['media']; ?>">
    <label for="<?php echo $this->id; ?>">
        <span><?php echo $this->label; ?></span>
    </label>
    <select name="champ<?php echo $this->champ['id']; ?>[]" id="<?php echo $this->id; ?>" class="<?php echo $this->classes; ?>" />
    <?php
    for ($i = 1970; $i <= 2030; $i++) {
        // L'année est-elle l'année courante ?
        $selected="";
        if ($this->value != "") {
            if ($i == $this->value) {
                $selected = ' selected="selected"';
            }
        } else {
            if ($i == date('Y')) {
                $selected = ' selected="selected"';
            }
        }
        ?>

                <option value="<?php echo $i; ?>"<?php echo $selected; ?>><?php echo $i; ?></option>
                    <?php
                }
                ?>
    </select>
</div>
