<div class="line<?php echo $this->champ['media']; ?>">
    <label for="<?php echo $this->id; ?>">
        <span><?php echo $this->label; ?> <?php echo in_array('form-oblig', explode(" ", $this->classes)) ? '<span class="required">*</span> ' : '' ; ?></span>
    </label>
    <input data-min-width="<?php  echo $this->params["CROP.WIDTH.MIN"]; ?>" type="text" name="champ<?php echo $this->champ['id']; ?>[]" id="<?php echo $this->id; ?>" class="<?php echo $this->classes; ?>" value="<?php echo $this->value; ?>" />
    
    <input type="hidden" class="extensions" value="<?php  echo $this->params["EXTENSIONS.ALLOW"]; ?>" />
    
    <div class="btn-a gradient-blue" <?php echo $this->value != '' ? '' : 'style="display:none;"'?>><a class="previsu" href="<?php echo ($this->value ? Slrfw\Library\Registry::get("base") . $this->uploadPath . DIRECTORY_SEPARATOR . $this->idGabPage . DIRECTORY_SEPARATOR . $this->value : '') ?>" target="_blank" class="previsu"><img src="img/back/voir.png" alt="Gérer"></a></div>
    
    <div class="btn-a gradient-blue" <?php echo $this->isImage ? '' : 'style="display:none;"'?>><a class="crop" href="#">Recadrer</a></div>

</div>