<style>
    #tableau td {
  overflow: hidden; /* this is what fixes the expansion */
  white-space: normal;
  word-wrap: break-word;
  max-width: 400px;

}

    
    
</style>

<form>
    <select name="id_version" method="get" onchange="$(this).parent().submit()">
        <?php
        foreach ($this->versions as $version) {
            ?>
            <option <?php echo BACK_ID_VERSION == $version['id'] ? 'selected="selected"' : ''; ?> value="<?php echo $version['id'] ?>"><?php echo $version['nom'] ?></option>
            <?php
        }
        ?>
    </select>
</form>

<h1><?php echo $this->config["table"]["title"] ?></h1>



<table cellpadding="0" width="100%" style="margin-top:0px;" cellspacing="0" border="0" class="display" id="tableau">
    <thead>
        <tr>
            <?php
            foreach ($this->config["columns"] as $column) {
                if (isset($column["show"]) && $column["show"]) {
                    ?>
                    <th  class="<?php echo isset($column["editable"]) && $column["editable"] ? "editable" : ""; ?>" width="25%"><?php echo $column["title"]; ?></th>
                    <?php
                }
            }
            ?>

        </tr>
    </thead>
    <tbody>

    </tbody>
    <tfoot>
        <tr>
            <?php
            foreach ($this->config["columns"] as $column) {
                if (isset($column["show"]) && $column["show"]) {
                    ?>
                    <th width="25%"><?php echo $column["title"]; ?></th>
                    <?php
                }
            }
            ?>
        </tr>
    </tfoot>
</table>
<script type="text/javascript">
                
    $(document).ready(function() {
        var oTable = $('#tableau').dataTable( {
            "bJQueryUI": true,
            'oLanguage': {
                "sProcessing": "Chargement...",
                "sLengthMenu": "Montrer _MENU_ <?php echo $this->config["table"]["title_item"] ?>s par page",
                "sZeroRecords": "Aucun<?php echo $this->config["table"]["suffix_genre"] ?> <?php echo $this->config["table"]["title_item"] ?> trouvé<?php echo $this->config["table"]["suffix_genre"] ?>",
                "sEmptyTable": "Pas de <?php echo $this->config["table"]["title_item"] ?>",
                "sInfo": "<?php echo $this->config["table"]["title_item"] ?>s _START_ à  _END_ sur _TOTAL_ <?php echo $this->config["table"]["title_item"] ?>s",
                "sInfoEmpty": "Aucun<?php echo $this->config["table"]["suffix_genre"] ?> <?php echo $this->config["table"]["title_item"] ?>",
                "sInfoFiltered": "(filtre sur _MAX_ <?php echo $this->config["table"]["title_item"] ?>s)",
                "sInfoPostFix": "",
                "sSearch": "Chercher:",
                "sUrl": "",
                "oPaginate": {
                    "sFirst": "",
                    "sPrevious": "",
                    "sNext": "",
                    "sLast": ""
                }
            },
            "bProcessing": true,
            "bServerSide": true,
            "sAjaxSource": "<?php echo $_GET["controller"]; ?>/json.html"
            

        } );
                
        $('td', oTable.fnGetNodes()).livequery(function() {
            if(!$("#tableau thead tr th").eq($(this).index()).hasClass("editable"))
                return true;
            /* Apply the jEditable handlers to the table */
            $(this).editable( '<?php echo $_GET["controller"]; ?>/editable.html', {
                indicator : 'Sauvegarde en cours ...',
                placeholder   : 'Cliquer pour éditer ...',
                "callback": function( sValue, y ) {
                    var aPos = oTable.fnGetPosition( this );
                    oTable.fnUpdate( sValue, aPos[0], aPos[1] );
                },
                "submitdata": function ( value, settings ) {
                    return {
                        "row_id": this.parentNode.getAttribute('id'),
                        "column": oTable.fnGetPosition( this )[2]
                    };
                },
                "height": "14px"
            } );
        })
        
    });
</script>