<!DOCTYPE html>
<!--[if lt IE 7]>      <html lang="<?php echo strtolower(SUF_VERSION); ?>" class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html lang="<?php echo strtolower(SUF_VERSION); ?>" class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html lang="<?php echo strtolower(SUF_VERSION); ?>" class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!--> <html lang="<?php echo strtolower(SUF_VERSION); ?>" class="no-js"> <!--<![endif]-->
    <head>
        <title><?php echo $this->seo->getTitle(); ?></title>
        <meta name="description" content="<?php echo $this->seo->getDescription(); ?>" />
        <meta name="keywords" lang="<?php echo strtolower(SUF_VERSION); ?>" content="<?php echo $this->seo->showKeywords(); ?>" />


        <meta charset="UTF-8" />
        <meta name="language" content="<?php echo strtolower(SUF_VERSION); ?>" />
        <meta name="robots" content="<?php echo $this->seo->getIndex(); ?>index, <?php echo $this->seo->getFollow(); ?>follow, all" />
        <meta name="googlebot" content="<?php echo $this->seo->getIndex(); ?>index, <?php echo $this->seo->getFollow(); ?>follow, all" />

        <meta name="msvalidate.01" content="" />
        <meta name="y_key" content="" />
        <meta name="google-site-verification" content="" />
        <meta name="author" content="Solire" />
        <base href="<?php echo $this->Url; ?>" />

<?php
if ($this->seo->getUrlCanonical() != "") {
    ?>
        <link rel="canonical" href="<?php echo $this->seo->getUrlCanonical(); ?>"/>
    <?php
}
?>



<?php echo $this->cssComponents; ?>


        <script src="js/jquery/jquery-1.7.min.js"></script>
        <!--[if IE]>
            <script src="js/html5.js"></script>
        <![endif]-->
<?php echo $this->jsComponents; ?>



    </head>
    <body role="document">
        <?php 
        if ($this->utilisateurAdmin->isConnected()) {
            $this->add("toolbar.phtml");
        }
        ?>
        

        <header role="banner">
            <?php $this->add("menu.phtml"); ?>
        </header>
        <!-- End header -->
        
        <div class="ariane" itemprop="breadcrumb"><?php $this->add("breadcrumbs.phtml"); ?></div>


        <?php $this->content(); ?>


        <footer>


        </footer>
        <!-- End footer -->


        <script type="text/javascript">
            
            var _gaq = _gaq || [];
            _gaq.push(['_setAccount', '<?php echo $this->google_analytics; ?>']);
            _gaq.push(['_setDomainName', 'none']);
            _gaq.push(['_setAllowLinker', true]);
            _gaq.push(['_trackPageview']);
 
            (function() {
                var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
                ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
                var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
            })();
            
        </script>
    </body>
</html>



