    <div id="menu">
        <ul>
<?php foreach ($this->rubriques as $rubrique) { $pages = $rubrique->getChildren(); ?>
            <li>
                <a href="<?php echo $rubrique->getMeta('rewriting'); ?>/<?php echo count($pages) == 0 || $rubrique->getMeta("id") == "5" ? '' : $pages[0]->getMeta('rewriting') . '.html'; ?>"><?php echo $rubrique->getMeta('titre'); ?></a>
                <dl style="display:none;">
<?php foreach ($pages as $page) {?>
                    <dt>
<?php if ($page->getMeta("id_gabarit") == 1) { $firstChild = $page->getFirstChild(); if ($firstChild) { ?>
                        <a href="<?php echo $rubrique->getMeta('rewriting'); ?>/<?php echo $page->getMeta('rewriting') . '/' . $firstChild->getMeta('rewriting') . '.html'; ?>"><?php echo $page->getMeta('titre'); ?></a>
<?php }} else { ?>
                        <a href="<?php echo $rubrique->getMeta('rewriting'); ?>/<?php echo $page->getMeta('rewriting') . '.html'; ?>"><?php echo $page->getMeta('titre'); ?></a>
<?php } ?>
                    </dt>
<?php } ?>
                </dl>
            </li>
<?php } ?>

        </ul>
    </div>

<?php if (count($this->fil_ariane) > 0) { ?>
    <div id="fil_ariane">
        <a href=".">Accueil</a>
<?php foreach ($this->fil_ariane as $fil) { if ($fil['url']) { ?>
        &gt; <a href="<?php echo $fil['url']; ?>"><?php echo $fil['label']; ?></a>
<?php } else { ?>
        &gt; <span><?php echo $fil['label']; ?></span>
<?php }} ?>
    </div>
<?php } ?>