<style>body { padding-top: 40px; }</style>


<div class="navbar navbar-fixed-top">
    <div class="navbar-inner">
        <div class="container-fluid">
            <a href="" class="brand"><img src="img/back/gray_dark/home_16x16.png"> <?php echo $this->site; ?></a>




            <ul class="nav pull-right">
                <li>
                    <?php
                    if (isset($this->page) && is_object($this->page)) {
                        ?>
                        <?php
                        if ($this->page->getMeta("visible") == 1) {
                            ?>
                            <a><span class="label label-success">Visible</span></a>
                            <?php
                        } else {
                            ?>
                            <a><span class="label label-info">Pas visible</span></a>
                            <?php
                        }
                        ?>
                        <?php
                    }
                    ?></li>
                <li class="divider-vertical"></li>
                <li class="dropdown">
                    <a data-toggle="dropdown" class="dropdown-toggle" href="#">Mode <?php echo $this->modePrevisualisation ? 'Prévisualisation' : 'Normal' ?>  <b class="caret"></b></a>
                    <ul class="dropdown-menu">
                        <li><a href="?mode_previsualisation=0">Normal</a></li>
                        <li><a href="?mode_previsualisation=1">Prévisualisation</a></li>
                    </ul>
                </li>
                <li class="divider-vertical"></li>
                <li class="dropdown">
                    <a data-toggle="dropdown" class="dropdown-toggle" href="#"><?php echo $this->utilisateurAdmin->get("nom"); ?> <?php echo $this->utilisateurAdmin->get("prenom"); ?> <b class="caret"></b></a>
                    <ul class="dropdown-menu">
                        <li><a href="back/sign/signout.html"><b>Déconnexion</b></a></li>
                    </ul>
                </li>
            </ul>    

        </div>

    </div>
</div>