<ul data-role="listview" data-inset="true" data-theme="c" data-dividertheme="a"> 
    <li data-theme="b">Agence Web à Lyon :</li>
    <li><a href="http://localhost/solire_framework/mobile/entreprise-et-communaute/" class="entreprise" data-transition="slide" title="Entreprise et communauté"><span>Entreprise et communauté</span></a></li>

    <li><a href="http://localhost/solire_framework/mobile/site-web-et-referencement/" class="solutions" data-transition="slide" title="Sites Internet et référencement"><span>Sites Internet et référencement</span></a></li>
    <li><a href="http://localhost/solire_framework/mobile/experiences-et-differences/" class="experiences" data-transition="slide" title="Expériences et différences"><span>Expériences et différences</span></a></li>

    <li data-theme="b" style="border:0px;">Exemple de réalisation Web :</li>
    <li data-theme="d"><p><a href="http://www.athome-enr.fr/" title="Visiter : athome-enr.fr" data-theme="b">athome-enr.fr</a> :<br/>Création et référencement d'un site BtoC / BtoB</p></li>

</ul> 