<!doctype html public "-//W3C//DTD HTML 4.0//EN">
<html>
    <head>
        <title>Connexion</title>
        <meta name="ROBOTS" content="noindex, nofollow" />
        <meta name="GOOGLEBOT" content="noindex, nofollow" />

        <base href="<?php echo $this->url; ?>" />

        <link type="text/css" rel="stylesheet" media="screen" href="http://www.solire.fr/style_solire_fw/css/back/newstyle-1.1.css" />
        <link rel="stylesheet" href="css/sticky.css" type="text/css" media="screen" title="" charset="utf-8" />
        <style>

            @font-face {
                font-family: 'FontomasCustomRegular';
                src: url('font/fontomas-webfont.eot');
                src: url('font/fontomas-webfont.eot?#iefix') format('embedded-opentype'),
                    url('font/fontomas-webfont.woff') format('woff'),
                    url('font/fontomas-webfont.ttf') format('truetype'),
                    url('font/fontomas-webfont.svg#FontomasCustomRegular') format('svg');
                font-weight: normal;
                font-style: normal;
            }


            [data-icon]:after {
                color: #888;
                content: attr(data-icon);
                font-family: 'FontomasCustomRegular';
                left: 8px;
                position: absolute;
                top: 16px;
                width: 30px;
            }

            form label {
                position: relative;
                width: 20px;
            }
            form input.mini {
                margin-top: 5px;
                width: 180px;
                padding: 3px 0px 3px 32px;
                -webkit-transition: width 1s ease;
                -moz-transition: width 1s ease;
                -o-transition: width 1s ease;
                -ms-transition: width 1s ease;
                transition: width 1s ease;
            }

            form input.mini:focus {
                width: 220px;
            }

            input:-moz-placeholder {
                color: #BEBEBE;
                width: 130px;
                font-style: italic;
            }
            input:hover {
                color: #666666;
            }
            input:focus {
                color: #666666;
            }

            .top-right, .top-left {
                top: -3px;
            }
            .btn-a {
                margin-left: 38px;
                margin-top: 5px;
                font-size: 12px;
                padding: 6px 18px;
                position: relative;
            }

        </style>
        <?php echo $this->javascript; ?>
        <script type="text/javascript" src="js/jquery/vibrate.js"></script>
        <script type="text/javascript">

            $(document).ready(function() {

                $("#sign-in").submit( function(e) {
                    e.preventDefault()
                    // configurations for the buzzing effect. Be careful not to make it too annoying!
                    var conf = {
                        frequency: 5000,
                        spread: 15,
                        duration: 600
                    };

                    var tthis = $(this);
                    var ok = true;
                    var formu = tthis;
                    $.post(formu.attr('action'), formu.serialize(), function(data){
                        if(data.success) {
                            $.sticky(data.message, "success")
                            $(formu).delay(800).queue(function(){
//                                $("#sign-in").unbind("submit")
//                                formu.submit();
                                document.location.href = formu.attr('action');
                            })
                        } else {
                            formu.parents("article:first").vibrate(conf);
                            // let's also display a notification
                            $.sticky(data.message, "error")

                            // clear the fields to discourage brute forcing :)
                            $("#log").val("");
                            $("#pwd").val("");
                        }


                    }, 'json' );






                });

            });


        </script>
        <script type="text/javascript">
            var keypressaction = function(event){
                if(event.keyCode == 13) $('.formsubmit-signin').trigger('click');
            }

            $(document).bind('keypress', keypressaction);
        </script>
    </head>
    <body style="background:#efefef;">
    <section>

        <article style="margin-top:15%; margin-right:auto; margin-left:auto; width:356px; padding:20px;box-shadow:3px 2px 5px #BFBFBF">
            <form id="sign-in" method="post" action="<?php echo $this->action; ?>">
                <fieldset>
                    <legend><b>Module d'administration</b></legend>

                    <div class="line">
                        <label data-icon="u" for="log"></label>
                        <input type="text" placeholder="Identifiant" name="log" id="log" class="form-controle form-oblig form-mix mini" size="50" maxlength="100" />
                    </div>

                    <div class="line">
                        <label data-icon="p" for="pwd"></label>
                        <input type="password" placeholder="Mot de passe" name="pwd" id="pwd" class="form-controle form-oblig form-mix mini" size="50" maxlength="100" />
                    </div>

                    <div class="">
                            <button class="btn-a gradient-green" type="submit">Connexion</button>
                </fieldset>
            </form>
        </article>
    </section>
</body>
</html>
