<div class="line">
    <label for="<?php echo $this->id; ?>">
        <span><?php echo $this->label; ?> <?php echo in_array('form-oblig', explode(" ", $this->classes)) ? '<span class="required">*</span> ' : '' ; ?></span>
    </label>
    <input type="checkbox" name="champ<?php echo $this->champ['id']; ?>[]" id="<?php echo $this->id; ?>" class="<?php echo $this->classes; ?>"<?php echo ($this->value > 0 ? ' checked="checked"' : '') ?> />
</div>