<div class="line form-line">
    <div class="line">
        <label for="<?php echo $this->id; ?>">
            <span><?php echo $this->label; ?> <?php echo in_array('form-oblig', explode(" ", $this->classes)) ? '<span class="required">*</span> ' : '' ; ?></span>
            <br />
            <br />
            <span class="switch-editor"><span>html</span>&nbsp;<span class="translucide">visuel</span></span>
        </label>
        
        <textarea name="champ<?php echo $this->champ['id']; ?>[]" id="<?php echo $this->id; ?>" class="<?php echo $this->classes; ?> tiny" rows="5" cols="20"><?php echo $this->value; ?></textarea>
    </div>
    
    <div class="line form-other-line" style="display:none;">
        <label class="form-other-flag"></label>
        <span style="display:inline-block; width: 500px; height: 290px; border-left:1px solid #CCC; border-right:1px solid #CCC; border-top:1px solid #CCC; border-bottom:1px solid #CCC;">
            <iframe class="form-other-elmt"></iframe>
        </span>
    </div>
</div>
