<div class="form-elmt line">
    <div class="line">
        <label for="<?php echo $this->id; ?>">
            <span><?php echo $this->label; ?> <?php echo in_array('form-oblig', explode(" ", $this->classes)) ? '<span class="required">*</span> ' : '' ; ?></span>
            <br />
            <br />
            <span class="switch-editor"><span>html</span>&nbsp;<span class="translucide">visuel</span></span>
        </label>
        
        <textarea name="champ<?php echo $this->champ['id']; ?>[]" id="<?php echo $this->id; ?>" class="<?php echo $this->classes; ?> tiny" rows="5" cols="20"><?php echo $this->value; ?></textarea>
    </div>
    
    <div class="line form-other-line" style="display:none;">
        <iframe class="form-other-elmt"></iframe>
    </div>
</div>
