<?php if (count($this->pages) > 0) { foreach ($this->pages as $page) { ?>


<fieldset class="sort-elmt" id="gab_page_<?php echo $page->getMeta('id'); ?>" style="margin-left:30px;">

    <legend title="<?php echo $page->getMeta('rewriting') ?>">
        <?php echo $page->getMeta('titre'); ?><?php if ($page->getMeta('nbre_enfants') > 0) { ?> - <i><span class="page-nbre-enfants"><?php echo $page->getMeta('nbre_enfants'); ?></span> page(s)</i><?php } ?>
    </legend>
    <div class="sort-box" style="display:none;"></div>

    <div class="line cat-modif">

        <div style="float:left;">
            <?php if ($this->utilisateur->get("niveau") == "solire" || $this->gabarits[$page->getMeta("id_gabarit")]["sortable"]) { ?>
                <a title="Déplacer '<?php echo $page->getMeta('titre'); ?>'" class="button bleu sort-move" href="#"><span class="bleu"><img alt="Déplacer" src="img/back/deplacer.png" /></span></a>
            <?php } ?>
            <?php if ($this->utilisateur->get("niveau") == "solire" || $this->gabarits[$page->getMeta("id_gabarit")]["editable"]) { ?>
                <a title="Modifier '<?php echo $page->getMeta('titre'); ?>'" class="button bleu" href="page/display.html?id_gab_page=<?php echo $page->getMeta('id'); ?>"><span class="bleu"><img alt="Modifier" src="img/back/voir.png" /></span></a>
            <?php } ?>
            <?php if ($this->utilisateur->get("niveau") == "solire" || $this->gabarits[$page->getMeta("id_gabarit")]["make_hidden"] || $page->getMeta('visible') == 0) { ?>
                <a title="Rendre visible '<?php echo $page->getMeta('titre'); ?>'" class="button bleu"><span style="padding-top:8px;" class="bleu"><input type="checkbox" class="rendrevisible"<?php echo $page->getMeta('visible') > 0 ? ' checked="checked"' : ''; ?><?php echo $page->getMeta('rewriting') ==  "" ? ' disabled="disabled"' : ''; ?> /></span></a>
            <?php } ?>
        </div>

        <div style="float:right;">
            <a title="Supprimer '<?php echo $page->getMeta('titre'); ?>'" style="float:right; display:<?php echo $page->getMeta('nbre_enfants') > 0 ? 'none' : 'block'; ?>;" class="button bleu supprimer" href="#"><span class="bleu"><img alt="Supprimer" src="img/back/supprimer.png"></span></a>
        </div>

    </div>

</fieldset>

<!--<div id="gab_page_<?php echo $page->getMeta('id') ?>" class="sort-elmt ligne">
            
    <a href="#" class="button bleu supprimer" style="float: right;"><span class="bleu"><img alt="Supprimer" src="img/back/supprimer.png"></span></a>

    <a href="#" class="button bleu sort-move"><span class="bleu"><img alt="déplacer" src="img/back/deplacer.png"></span></a>

    <a class="button bleu"><span style="padding-top:8px;" class="bleu"><input type="checkbox" class="rendrevisible"<?php echo $page->getMeta('visible') > 0 ? ' checked="checked"' : ''; ?> /></span></a>

    <a href="page/display.html?id_gab_page=<?php echo $page->getMeta('id') ?>" style="margin-left:20px;" title="<?php echo $page->getMeta('rewriting') ?>"><b><?php echo $page->getMeta('titre') ?></b></a>

</div>-->

<?php }} else { ?>

        <div>Aucune page dans ce dossier</div>
        
<?php } ?>