<?php
if (count($this->pages) > 0) {
    foreach ($this->pages as $page) {
        ?>


        <fieldset class="sort-elmt" id="gab_page_<?php echo $page->getMeta('id'); ?>" style="margin-left:30px;">

            <legend title="<?php echo $page->getMeta('rewriting') ?>">
                <?php if ($page->getMeta('nbre_enfants') > 0) { ?>
                    <span class="ui-icon-plus"></span>
                    <?php
                }
                ?>
                <?php echo $page->getMeta('titre'); ?>
                <br />
                <?php if ($page->getMeta("date_modif") != "0000-00-00 00:00:00" && $page->getMeta("rewriting") != "") { ?>
                    <span class="board-human-time" style="color: inherit">Dernière édition <?php echo $page->getMeta("date_modif") != "0000-00-00 00:00:00" ? Slrfw\Library\Tools::RelativeTime(strtotime($page->getMeta("date_modif"))) : ''; ?></span>
                    <?php
                }
                ?>
                <span class="page-info" style="color: inherit">    
                    <?php if ($page->getMeta("id_gabarit") != 1 && $page->getMeta("id_gabarit") != 2) { ?>
                        <?php if ($page->getMeta("date_modif") != "0000-00-00 00:00:00" && $page->getMeta("rewriting") != "") { ?>
                            |
                            <?php
                        }
                        ?>
                        <i>Type : <?php echo $this->gabarits[$page->getMeta("id_gabarit")]["label"] ?></i>
                    <?php } ?>
                    <?php if ($page->getMeta('nbre_enfants') > 0) { ?> 
                        |
                        <i><span class="page-nbre-enfants"><?php echo $page->getMeta('nbre_enfants'); ?></span> page(s)</i>
                    <?php } ?>

                </span>

            </legend>
            <div class="sort-box" style="display:none;"></div>

            <div class="line cat-modif">


                <div style="float:left;">
                    <?php if ($this->utilisateur->get("niveau") == "solire" || $this->gabarits[$page->getMeta("id_gabarit")]["sortable"]) { ?>
                        <div class="btn-a gradient-blue fl" ><a class="sort-move" title="Déplacer '<?php echo $page->getMeta('titre'); ?>'" href="#"><img alt="Déplacer" src="img/deplacer.png" /></a></div>
                    <?php } ?>
                    <?php if ($this->utilisateur->get("niveau") == "solire" || $this->gabarits[$page->getMeta("id_gabarit")]["editable"]) { ?>
                        <div class="btn-a gradient-blue fl" ><a title="Modifier '<?php echo $page->getMeta('titre'); ?>'" href="page/display.html?id_gab_page=<?php echo $page->getMeta('id'); ?>"><img alt="Modifier" src="img/white/pen_alt_stroke_16x16.png" /></a></div>
                    <?php } ?>
                    <?php if (($this->utilisateur->get("niveau") == "solire" || $this->gabarits[$page->getMeta("id_gabarit")]["make_hidden"] || $page->getMeta('visible') == 0) && $page->getMeta('rewriting') != "") { ?>
                        <div class="btn-a gradient-blue fl" ><a title="Rendre visible '<?php echo $page->getMeta('titre'); ?>'" style="padding: 8px 15px 6px;"><input type="checkbox" class="rendrevisible"<?php echo $page->getMeta('visible') > 0 ? ' checked="checked"' : ''; ?> /></a></div>
                    <?php } ?>   
                    <?php if ($page->getMeta("rewriting") == "") { ?>
                        <div class="btn-a gradient-red fl" style=""><a href="page/display.html?id_gab_page=<?php echo $page->getMeta('id'); ?>" style="line-height: 16px;">Non traduit</a></div>
                    <?php } ?>

                </div>

                <?php if ($this->utilisateur->get("niveau") == "solire" || $this->gabarits[$page->getMeta("id_gabarit")]["deletable"]) { ?>
                    <div style="float:right;">
                        <div class="btn-a gradient-blue" ><a title="Supprimer '<?php echo $page->getMeta('titre'); ?>'" style="float:right; display:<?php echo $page->getMeta('nbre_enfants') > 0 ? 'none' : 'block'; ?>;" class="supprimer" href="#"><img alt="Supprimer" src="img/white/trash_stroke_16x16.png"></a></div>
                    </div>
                <?php } ?>

            </div>

        </fieldset>

                                                                           
        <?php
    }
} else {
    ?>

    <div>Aucune page dans ce dossier</div>

<?php } ?>