<h1>Gestion des pages</h1>

<?php $this->add('breadcrumbs.phtml'); ?>

<h2><?php echo ($this->page->getMeta() ? 'Modification de ' : 'Création de ') . strtolower($this->page->getGabarit()->getLabel()); ?></h2>



<?php echo $this->form; ?>


<?php
if (isset($_GET["popup"]) && $_GET["popup"] == "more") {
    ?>

    <div class="modal  hide fade" id="modalMore" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
        <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
            <h3 id="myModalLabel">Que voulez-vous faire ?</h3>
        </div>
        <div class="modal-body">

            <dl class="">

                <?php
                if ($this->page->getMeta("rewriting") != "") {
                    if ($this->page->getGabarit()->getMake_hidden()
                            || $this->utilisateur->get("niveau") == "solire"
                            || !$this->page->getMeta("visible")
                    ) {
                        echo '<dt>Gérer la visibité :</dt><br /><dd><img src="img/flags/png/' . strtolower($this->versions[BACK_ID_VERSION]['suf']) . '.png" alt="" />';

                        echo ' <input class="visible-lang visible-lang-' . $this->page->getMeta("id") . '-' . BACK_ID_VERSION . '" style="margin:0;" value="'
                        . $this->page->getMeta("id") . '|' . BACK_ID_VERSION . '" id="visible-' . BACK_ID_VERSION . '" style="margin:0;" '
                        . ($this->page->getMeta("visible") ? 'checked="checked"' : '') . ' type="checkbox" /><dd>';
                    }
                }
                ?>
                <br />
                <br />
                <dt>Editer une autre page :</dt>
                <br />
                <dd>
                    <div>
                        <input type="text" placeholder="Recherche" class="search live-search ui-autocomplete-input" autocomplete="off" role="textbox" aria-autocomplete="list" aria-haspopup="true">
                    </div>
                </dd>
                <br />

                <dt>Créer un nouveau contenu :</dt>
                <br />
                <dd>
                    <div style="min-height: 50px;">
                        <?php $this->add("template/button.phtml"); ?>
                    </div>
                </dd>
            </dl>

        </div>
        <div class="modal-footer">
            <button class="btn-a gradient-grey btn-large" onclick="var link = $('.back-to-list a').attr('href');window.location = link;">Quitter</button>
            <button class="btn-a gradient-grey btn-large" data-dismiss="modal" onclick="$('.formprev').click()" aria-hidden="true"><b>Prévisualiser</b></button>
            <button class="btn-a gradient-blue btn-large" data-dismiss="modal" aria-hidden="true">Continuer l'édition de cette page</button>
        </div>
    </div>
    <?php
}
?>


<style>


    .loading-overlay {
        background: rgba(0,0,0,0.6);
        position:fixed;
        width:100%;
        height:100%;
        z-index:101
    }

    /* LOADING SPINNER*/
    .circle {
        background-color: rgba(0,0,0,0);
        border:5px solid rgba(0,183,229,0.9);
        opacity:.9;
        border-right:5px solid rgba(0,0,0,0);
        border-left:5px solid rgba(0,0,0,0);
        border-radius:50px;
        box-shadow: 0 0 35px #2187e7;
        width:50px;
        height:50px;
        margin:0 auto;
        -moz-animation:spinPulse 1s infinite ease-in-out;
        -webkit-animation:spinPulse 1s infinite linear;
    }
    .circle1 {
        background-color: rgba(0,0,0,0);
        border:5px solid rgba(0,183,229,0.9);
        opacity:.9;
        border-left:5px solid rgba(0,0,0,0);
        border-right:5px solid rgba(0,0,0,0);
        border-radius:50px;
        box-shadow: 0 0 15px #2187e7; 
        width:30px;
        height:30px;
        margin:0 auto;
        position:relative;
        top:-50px;
        -moz-animation:spinoffPulse 1s infinite linear;
        -webkit-animation:spinoffPulse 1s infinite linear;
    }
    @-moz-keyframes spinPulse {
        0% { -moz-transform:rotate(160deg); opacity:0; box-shadow:0 0 1px #2187e7;}
    50% { -moz-transform:rotate(145deg); opacity:1; }
    100% { -moz-transform:rotate(-320deg); opacity:0; }
    }
    @-moz-keyframes spinoffPulse {
        0% { -moz-transform:rotate(0deg); }
    100% { -moz-transform:rotate(360deg);  }
    }
    @-webkit-keyframes spinPulse {
        0% { -webkit-transform:rotate(160deg); opacity:0; box-shadow:0 0 1px #2187e7; }
    50% { -webkit-transform:rotate(145deg); opacity:1;}
    100% { -webkit-transform:rotate(-320deg); opacity:0; }
    }
    @-webkit-keyframes spinoffPulse {
        0% { -webkit-transform:rotate(0deg); }
    100% { -webkit-transform:rotate(360deg); }
    }

    .border-none, .border-none tr, .border-none  td {
        border: none;
    }

    .top, .bottom {
        border: 0px;
        padding: 0px;
    }

    .modal-big {
        width: 900px;
        margin-left: -450px;
    }

    @media (max-width: 942px) {
        .modal-big {
            width: auto;
            margin-left: auto;
        }
    }
</style>

<div class="modal hide fade" id="modalCrop" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
        <h3 id="myModalLabel">Recadrer</h3>
    </div>
    <div class="modal-body">
        <table class="border-none" border="0">
            <tr>
                <td style="border:1px solid #CFCFCF">

                </td>
                <td style="vertical-align:top">

                    <form class="form-crop form-horizontal" action="media/crop.html" method="post">
                        <fieldset class="img-info">
                            <legend>Information</legend>
                            <dl class="dl-horizontal">
                                <dt style="width: 180px;">Largeur minimale attendue</dt>
                                <dd style="margin-left: 190px;"><span id="minwidthShow"></span>px</dd>
                            </dl>


                        </fieldset>
                        <fieldset>
                            <legend>Sélection</legend>
                            <div class="control-group">
                                <label class="control-label" for="wShow">Largeur</label>
                                <div class="controls">
                                    <input type="text" style="width: 60px" class="wShow spinner" id="wShow" placeholder="Largeur" value="" />
                                </div>
                            </div>
                            <div class="control-group">
                                <label class="control-label" for="hShow">Hauteur</label>
                                <div class="controls">
                                    <input type="text" style="width: 60px" class="hShow spinner" id="hShow" placeholder="Hauteur" value="" />
                                </div>
                            </div>
                        </fieldset>
                        <fieldset>
                            <legend>Enregistrement</legend>
                            <label class="radio">
                                <input type="radio" checked="checked" name="force-width">Respecter la largeur minimum
                            </label>
                            <label class="radio">
                                <input type="radio"  value="1" name="force-width">Forcer la taille en fonction de la sélection
                            </label>
                            <input type="hidden" id="filepath" name="filepath" />
                            <input type="hidden" id="x" name="x" />
                            <input type="hidden" id="y" name="y" />
                            <input type="hidden" id="w" name="w" />
                            <input type="hidden" id="h" name="h" />
                            <input type="hidden" id="minwidth" name="minwidth" />
                        </fieldset>
                    </form>
                    <!--                    <div style="width:100px;height:100px;overflow:hidden;">
                                            <img src="" id="crop-preview" alt="Preview" class="jcrop-preview" />
                                        </div>-->
                </td>
            </tr>

        </table>

    </div>
    <div class="modal-footer">
        <button class="btn" data-dismiss="modal" aria-hidden="true">Annuler</button>
        <button class="btn btn-primary form-crop-submit">Recadrer</button>
    </div>
</div>



