<?php
if (stristr($_SERVER["HTTP_ACCEPT"], "application/xhtml+xml") && !$this->ajax) {
    echo '<?xml version="1.0" encoding="UTF-8"?>';
    $contentType = "application/xhtml+xml; charset=utf-8";
} else {
    $contentType = "text/html; charset=utf-8";
}
?> 
<!DOCTYPE html PUBLIC "-//WAPFORUM//DTD XHTML Mobile 1.0//EN" "http://www.wapforum.org/DTD/xhtml-mobile10.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="fr" lang="fr">
    <head>
        <title><?php echo $this->seo->getTitle(); ?></title>
        <meta name="description" content="<?php echo $this->seo->getDescription(); ?>" />
        <meta name="keywords" lang="fr" content="<?php echo $this->seo->showKeywords(); ?>" />
        <meta name="robots" content="<?php echo $this->seo->getIndex(); ?>index, <?php echo $this->seo->getFollow(); ?>follow, all" />
        <meta name="googlebot" content="<?php echo $this->seo->getIndex(); ?>index, <?php echo $this->seo->getFollow(); ?>follow, all" />
        <meta name="msvalidate.01" content="" />
        <meta name="y_key" content="" />
        <meta name="google-site-verification" content="" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <meta http-equiv="Content-Type" content="<?php echo $contentType; ?>"/>
        <meta name="language" content="fr" />
        <meta name="author" content="Solire" />
        <link rel="apple-touch-icon" href="http://www.solire.fr/apple-touch-icon.png" />
        <link type="text/css" media="" rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/jquery.mobile/1.1.0/jquery.mobile-1.1.0.min.css" />
        <?php echo $this->cssComponents; ?>
        <script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js"></script>
        <script type="text/javascript">$(document).bind("mobileinit",function(){$.mobile.loadingMessage="Chargement ...";$.mobile.loadingMessageTextVisible=true})</script>
        <script type="text/javascript" src="https://ajax.aspnetcdn.com/ajax/jquery.mobile/1.1.0/jquery.mobile-1.1.0.min.js"></script>
        <?php echo $this->jsComponents; ?>
    </head>
    <body>
        <div data-role="page">
            <div data-role="header">
                <h1>Solire</h1>
                <a href="<?php echo $this->Url; ?>" data-icon="home" data-iconpos="notext" data-direction="reverse">Home</a>
                <a href="<?php echo $this->Url; ?>" data-rel="back" data-iconpos="notext" data-icon="back"></a>
                <div data-role="navbar" data-iconpos="left">
                    <ul>
                        <?php foreach ($this->rubriques as $key => $rubrique) {
                            ?>
                            <li><a <?php echo isset($_GET["rub"]) && $rubrique->getMeta("rewriting") == $_GET["rub"] ? 'class="ui-btn-active ui-state-persist"' : ''; ?> href="<?php echo $this->Url; ?><?php echo $rubrique->getMeta('rewriting'); ?>.html" data-theme="c"><?php echo $rubrique->getMeta('titre'); ?></a></li>
                        <?php } ?>
                    </ul>
                </div>
            </div>
            <div data-role="content"><?php $this->content(); ?></div>
            <div data-theme="a" data-role="footer" data-position="fixed"><h3>Solire.fr</h3></div>
        </div>
        <script type="text/javascript">var _gaq=_gaq||[];_gaq.push(["_setAccount","<?php echo $this->google_analytics; ?>"]);_gaq.push(["_setDomainName","none"]);_gaq.push(["_setAllowLinker",true]);_gaq.push(["_trackPageview"]);(function(){var a=document.createElement("script");a.type="text/javascript";a.async=true;a.src=("https:"==document.location.protocol?"https://ssl":"http://www")+".google-analytics.com/ga.js";var b=document.getElementsByTagName("script")[0];b.parentNode.insertBefore(a,b)})();$("[data-role=page]").live("pageshow",function(a,b){try{if(location.hash){url=location.hash}else{url=defaulturl}_gaq.push(["_trackPageview",url])}catch(c){}})
        </script>
    </body>
</html>