<div class="line<?php echo $this->champ['media']; ?>">
    <label for="<?php echo $this->id; ?>">
        <span><?php echo $this->label; ?></span>
    </label>
    <input type="text"  id="<?php echo $this->id; ?>" value="<?php echo $this->valueLabel; ?>" class="<?php echo $this->classes; ?> autocomplete-join" />
    <input type="hidden" value="<?php echo $this->value; ?>" name="champ<?php echo $this->champ['id']; ?>[]" id="<?php echo $this->id; ?>" class="<?php echo $this->classes; ?> join" />
    <input type="hidden" class="join-param join-table" value="<?php echo $this->params["TABLE.NAME"]; ?>" />
    <input type="hidden" class="join-param join-label_field" value="<?php echo $this->params["TABLE.FIELD.LABEL"]; ?>" />
    <input type="hidden" class="join-param join-query_filter" value="<?php echo $this->params["QUERY.FILTER"]; ?>" />
    <input type="hidden" class="join-param join-id_field" value="<?php echo $this->params["TABLE.FIELD.ID"]; ?>" />
</div>
